project:
  type: book

book:
  title: "Fantasy Football Analytics"
  author: "Isaac T. Petersen"
  date: today
  reader-mode: true
  page-footer:
    left: |
      Fantasy Football Analytics was written by <a href="https://psychology.uiowa.edu/people/isaac-petersen">Isaac T. Petersen</a>.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.png
  favicon: cover.png
  site-url: https://isaactpetersen.github.io/Fantasy-Football-Analytics-Textbook
  repo-url: https://github.com/isaactpetersen/Fantasy-Football-Analytics-Textbook
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
    number-sections: true
    code-fold: show
    code-line-numbers: true
    execute:
      error: true
    keep-md: true
    license: CC BY
    author-meta: "Isaac T. Petersen"
    date-meta: today
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png
