project:
  type: book

book:
  title: "Fantasy Football Analytics: Statistics, Prediction, and Empiricism Using R"
  subtitle: "Version 0.0.1"
  author: "Isaac T. Petersen"
  date: today
  #cover-image: ADD
  #cover-image-alt: ADD
  sharing: [twitter, facebook, linkedin]
  #doi: ADD
  #isbn: ADD
  keyword: fantasy football, fantasy football analytics, data analysis, statistical analysis, statistics, R software, prediction, empiricism
  license: "CC BY"
  reader-mode: true
  page-footer:
    left: |
      "Fantasy Football Analytics: Statistics, Prediction, and Empiricism Using R" was written by <a href="https://psychology.uiowa.edu/people/isaac-petersen">Isaac T. Petersen</a>.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: images/cover.png
  favicon: images/logo.png
  twitter-card: true
  open-graph: true
  site-url: https://isaactpetersen.github.io/Fantasy-Football-Analytics-Textbook
  repo-url: https://github.com/isaactpetersen/Fantasy-Football-Analytics-Textbook
  repo-branch: main
  repo-actions: [edit, source, issue]
  google-analytics: G-C3SNF7Y0PJ
  chapters:
    - index.qmd
    - intro.qmd
    - fantasy-football.qmd
    - getting-started.qmd
    - download-football-data.qmd
    - data-visualization.qmd
    - player-evaluation.qmd
    - draft.qmd
    - research-methods.qmd
    - basic-statistics.qmd
    - correlation.qmd
    - multiple-regression.qmd
    - mixed-models.qmd
    - causal-inference.qmd
    - cognitive-bias.qmd
    - actuarial.qmd
    - base-rates.qmd
    - evaluating-prediction-accuracy.qmd
    - mythbusters.qmd
    #- machine-learning.qmd
    - modern-portfolio-theory.qmd
    - cluster-analysis.qmd
    - factor-analysis.qmd
    - pca.qmd
    #- simulation.qmd
    - time-series-analysis.qmd
    - decision-making.qmd
    - sports-cognitive-psychology.qmd
    - references.qmd

bibliography: [references.bib, packages.bib]
csl: apa.csl
nocite: |
  @Corston2000

format:
  html:
    highlight-style: a11y
    theme:
      light: [cosmo, fonts/css/lora.css]
      dark: [cosmo, fonts/css/lora.css, theme-dark.scss]
    mainfont: Lora #gfonts::setup_font("lora", output_dir = "./fonts/"); gfonts::get_all_fonts()
    code-link: true
    number-sections: true
    code-fold: show
    code-line-numbers: true
    toc: true
    toc-depth: 5
    execute:
      error: true
      message: false
      warning: false
    keep-md: true
    link-external-newwindow: true
    embed-resources: false
    anchor-sections: true
    df-print: paged
    comments:
      hypothesis:
        theme: classic
        openSidebar: false
        showHighlights: whenSidebarOpen
      giscus:
        repo: isaactpetersen/Fantasy-Football-Analytics-Textbook
        repo-id: R_kgDOL6_f_A
        category: Chapter Comments
        category-id: DIC_kwDOL6_f_M4Cnvl7
        mapping: pathname
        reactions-enabled: true
        loading: lazy
        input-position: top
    #include-in-header:
    #  - "includes/google_analytics.html"
    include-before-body:
      - "includes/open-review.html"
    include-after-body:
    #  - "includes/disqus.html"
      - "includes/email_submit.html"
    #  - "includes/footer.html"
    license: CC BY
    author-meta: "Isaac T. Petersen"
    date-meta: today
  pdf:
    documentclass: krantz
    keep-tex: true
    include-in-header: latex/preamble.tex
    include-before-body: latex/before_body.tex
    include-after-body: latex/after_body.tex
    execute:
      error: true
      message: false
      warning: false
  epub:
    cover-image: images/cover.png
    execute:
      error: true
      message: false
      warning: false

lightbox: 
  match: auto
