
book:
  abstract: |
      This book is about learning statistics, prediction, and empiricism through the lens of fantasy football.
      It teaches readers how to use the free software R to perform fantasy football data analysis.
