<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Isaac T. Petersen">
<meta name="dcterms.date" content="today">
<title>16&nbsp; Base Rates – Fantasy Football Analytics: Statistics, Prediction, and Empiricism Using R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./evaluating-prediction-accuracy.html" rel="next">
<link href="./actuarial.html" rel="prev">
<link href="./images/logo.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-C3SNF7Y0PJ"></script><script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-C3SNF7Y0PJ', { 'anonymize_ip': true});
</script><script type="application/json" class="js-hypothesis-config">
{
  "theme": "clean",
  "openSidebar": false
}
</script><script async="" src="https://hypothes.is/embed.js"></script><script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script><link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
<meta property="og:title" content="16&nbsp; Base Rates – Fantasy Football Analytics: Statistics, Prediction, and Empiricism Using R">
<meta property="og:description" content="This book is about learning statistics, prediction, and empiricism through the lens of fantasy football. It teaches readers how to use the free software R to perform fantasy football data analysis.">
<meta property="og:site_name" content="Fantasy Football Analytics: Statistics, Prediction, and Empiricism Using R">
<meta name="twitter:title" content="16&nbsp; Base Rates – Fantasy Football Analytics: Statistics, Prediction, and Empiricism Using R">
<meta name="twitter:description" content="This book is about learning statistics, prediction, and empiricism through the lens of fantasy football. It teaches readers how to use the free software R to perform fantasy football data analysis.">
<meta name="twitter:card" content="summary">
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./base-rates.html"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Base Rates</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Fantasy Football Analytics: Statistics, Prediction, and Empiricism Using R</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/isaactpetersen/Fantasy-Football-Analytics-Textbook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=%7Curl%7C">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=%7Curl%7C">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=%7Curl%7C">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
</div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fantasy-football.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Intro to Football and Fantasy</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./getting-started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Getting Started with <code>R</code> for Data Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./download-football-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Download and Process NFL Football Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data Visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./player-evaluation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Player Evaluation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./draft.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">The Fantasy Draft</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./research-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Research Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basic-statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Basic Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Correlation Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multiple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Multiple Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mixed-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Mixed Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./causal-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Causal Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cognitive-bias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Heuristics and Cognitive Biases in Prediction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./actuarial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Judgment Versus Actuarial Approaches to Prediction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./base-rates.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Base Rates</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./evaluating-prediction-accuracy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Evaluation of Prediction/Forecasting Accuracy</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mythbusters.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Mythbusters: Putting Fantasy Football Beliefs/Anecdotes to the Test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./modern-portfolio-theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Modern Portfolio Theory</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cluster-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Cluster Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./time-series-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Time Series Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./decision-making.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Decision Making in the Context of Uncertainty</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#sec-baseRatesGettingStarted" id="toc-sec-baseRatesGettingStarted" class="nav-link active" data-scroll-target="#sec-baseRatesGettingStarted"><span class="header-section-number">16.1</span> Getting Started</a>
  <ul>
<li><a href="#sec-baseRatesLoadPackages" id="toc-sec-baseRatesLoadPackages" class="nav-link" data-scroll-target="#sec-baseRatesLoadPackages"><span class="header-section-number">16.1.1</span> Load Packages</a></li>
  </ul>
</li>
  <li><a href="#sec-baseRatesOverview" id="toc-sec-baseRatesOverview" class="nav-link" data-scroll-target="#sec-baseRatesOverview"><span class="header-section-number">16.2</span> Overview</a></li>
  <li>
<a href="#sec-probability" id="toc-sec-probability" class="nav-link" data-scroll-target="#sec-probability"><span class="header-section-number">16.3</span> Issues Around Probability</a>
  <ul>
<li>
<a href="#sec-probabilityTypes" id="toc-sec-probabilityTypes" class="nav-link" data-scroll-target="#sec-probabilityTypes"><span class="header-section-number">16.3.1</span> Types of Probabilities</a>
  <ul class="collapse">
<li><a href="#sec-baseRate" id="toc-sec-baseRate" class="nav-link" data-scroll-target="#sec-baseRate"><span class="header-section-number">16.3.1.1</span> Base Rate (Marginal Probability)</a></li>
  <li><a href="#sec-jointProbability" id="toc-sec-jointProbability" class="nav-link" data-scroll-target="#sec-jointProbability"><span class="header-section-number">16.3.1.2</span> Joint Probability</a></li>
  <li><a href="#sec-conditionalProbability" id="toc-sec-conditionalProbability" class="nav-link" data-scroll-target="#sec-conditionalProbability"><span class="header-section-number">16.3.1.3</span> Conditional Probability</a></li>
  </ul>
</li>
  <li><a href="#sec-inverseFallacy" id="toc-sec-inverseFallacy" class="nav-link" data-scroll-target="#sec-inverseFallacy"><span class="header-section-number">16.3.2</span> Confusion of the Inverse</a></li>
  <li>
<a href="#sec-bayesTheorem" id="toc-sec-bayesTheorem" class="nav-link" data-scroll-target="#sec-bayesTheorem"><span class="header-section-number">16.3.3</span> Bayes’ Theorem</a>
  <ul class="collapse">
<li><a href="#sec-bayesTheoremStandard" id="toc-sec-bayesTheoremStandard" class="nav-link" data-scroll-target="#sec-bayesTheoremStandard"><span class="header-section-number">16.3.3.1</span> Standard Formulation</a></li>
  <li><a href="#sec-bayesTheoremAlternative" id="toc-sec-bayesTheoremAlternative" class="nav-link" data-scroll-target="#sec-bayesTheoremAlternative"><span class="header-section-number">16.3.3.2</span> Alternative Formulation</a></li>
  <li><a href="#interim-summary" id="toc-interim-summary" class="nav-link" data-scroll-target="#interim-summary"><span class="header-section-number">16.3.3.3</span> Interim Summary</a></li>
  </ul>
</li>
  </ul>
</li>
  <li><a href="#sec-cabExample" id="toc-sec-cabExample" class="nav-link" data-scroll-target="#sec-cabExample"><span class="header-section-number">16.4</span> Cab Example</a></li>
  <li>
<a href="#sec-nateSilverExamples" id="toc-sec-nateSilverExamples" class="nav-link" data-scroll-target="#sec-nateSilverExamples"><span class="header-section-number">16.5</span> Nate Silver Examples</a>
  <ul>
<li><a href="#sec-nateSilverExample1" id="toc-sec-nateSilverExample1" class="nav-link" data-scroll-target="#sec-nateSilverExample1"><span class="header-section-number">16.5.1</span> Example 1: Is Your Partner Cheating on You?</a></li>
  <li><a href="#sec-nateSilverExample2" id="toc-sec-nateSilverExample2" class="nav-link" data-scroll-target="#sec-nateSilverExample2"><span class="header-section-number">16.5.2</span> Example 2: Does a Person Have Breast Cancer?</a></li>
  <li>
<a href="#sec-nateSilverExample3" id="toc-sec-nateSilverExample3" class="nav-link" data-scroll-target="#sec-nateSilverExample3"><span class="header-section-number">16.5.3</span> Example 3: Was it a Terrorist Attack?</a>
  <ul class="collapse">
<li><a href="#sec-nateSilverExample3A" id="toc-sec-nateSilverExample3A" class="nav-link" data-scroll-target="#sec-nateSilverExample3A"><span class="header-section-number">16.5.3.1</span> Example 3A: The First Plane Hit the World Trade Center</a></li>
  <li><a href="#sec-nateSilverExample3B" id="toc-sec-nateSilverExample3B" class="nav-link" data-scroll-target="#sec-nateSilverExample3B"><span class="header-section-number">16.5.3.2</span> Example 3B: The Second Plane Hit the World Trade Center</a></li>
  </ul>
</li>
  </ul>
</li>
  <li><a href="#sec-baseRateFantasyFootball" id="toc-sec-baseRateFantasyFootball" class="nav-link" data-scroll-target="#sec-baseRateFantasyFootball"><span class="header-section-number">16.6</span> Base Rates Applied to Fantasy Football</a></li>
  <li>
<a href="#sec-baseRateRookiePerformance" id="toc-sec-baseRateRookiePerformance" class="nav-link" data-scroll-target="#sec-baseRateRookiePerformance"><span class="header-section-number">16.7</span> Base Rate of Rookie Performance</a>
  <ul>
<li><a href="#sec-baseRateRookiePerformanceQBs" id="toc-sec-baseRateRookiePerformanceQBs" class="nav-link" data-scroll-target="#sec-baseRateRookiePerformanceQBs"><span class="header-section-number">16.7.1</span> Quarterbacks</a></li>
  <li><a href="#sec-baseRateRookiePerformanceRBs" id="toc-sec-baseRateRookiePerformanceRBs" class="nav-link" data-scroll-target="#sec-baseRateRookiePerformanceRBs"><span class="header-section-number">16.7.2</span> Running Backs</a></li>
  </ul>
</li>
  <li>
<a href="#sec-accountForBaseRates" id="toc-sec-accountForBaseRates" class="nav-link" data-scroll-target="#sec-accountForBaseRates"><span class="header-section-number">16.8</span> How to Account for Base Rates</a>
  <ul>
<li><a href="#sec-accountForBaseRatesActuarial" id="toc-sec-accountForBaseRatesActuarial" class="nav-link" data-scroll-target="#sec-accountForBaseRatesActuarial"><span class="header-section-number">16.8.1</span> Actuarial Formula</a></li>
  <li>
<a href="#sec-bayesianUpdating" id="toc-sec-bayesianUpdating" class="nav-link" data-scroll-target="#sec-bayesianUpdating"><span class="header-section-number">16.8.2</span> Bayesian Updating</a>
  <ul class="collapse">
<li><a href="#sec-diagnosticLikelihoodRatio" id="toc-sec-diagnosticLikelihoodRatio" class="nav-link" data-scroll-target="#sec-diagnosticLikelihoodRatio"><span class="header-section-number">16.8.2.1</span> Diagnostic Likelihood Ratio</a></li>
  <li><a href="#sec-probabilityNomogram" id="toc-sec-probabilityNomogram" class="nav-link" data-scroll-target="#sec-probabilityNomogram"><span class="header-section-number">16.8.2.2</span> Probability Nomogram</a></li>
  <li><a href="#sec-informalUpdating" id="toc-sec-informalUpdating" class="nav-link" data-scroll-target="#sec-informalUpdating"><span class="header-section-number">16.8.2.3</span> Informal Updating</a></li>
  </ul>
</li>
  </ul>
</li>
  <li><a href="#sec-baseRatesConclusion" id="toc-sec-baseRatesConclusion" class="nav-link" data-scroll-target="#sec-baseRatesConclusion"><span class="header-section-number">16.9</span> Conclusion</a></li>
  <li><a href="#sec-baseRatesSessionInfo" id="toc-sec-baseRatesSessionInfo" class="nav-link" data-scroll-target="#sec-baseRatesSessionInfo"><span class="header-section-number">16.10</span> Session Info</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/isaactpetersen/Fantasy-Football-Analytics-Textbook/edit/main/base-rates.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/isaactpetersen/Fantasy-Football-Analytics-Textbook/blob/main/base-rates.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li><li><a href="https://github.com/isaactpetersen/Fantasy-Football-Analytics-Textbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><div class="alert alert-info hints-alert">
  <div class="hints-icon">
    <i class="fa fa-comments-o"></i>
  </div>
  <div class="hints-container">
    <b>I need your help!</b>
    <p>
    I want your feedback to make the book better for you and other readers. If you find typos, errors, or places where the text may be improved, please let me know.
    The best ways to provide feedback are by <a href="https://github.com/isaactpetersen/Fantasy-Football-Analytics-Textbook">GitHub</a> or <a href="https://hypothes.is">hypothes.is</a> annotations.
    </p>

    <p>
      <i class="fa fa-github"></i>
      <a href="https://github.com/isaactpetersen/Fantasy-Football-Analytics-Textbook/issues">Opening an issue</a> or <a href="https://github.com/isaactpetersen/Fantasy-Football-Analytics-Textbook/pulls">submitting a pull request</a> on GitHub: <a href="https://github.com/isaactpetersen/Fantasy-Football-Analytics-Textbook">https://github.com/isaactpetersen/Fantasy-Football-Analytics-Textbook</a>
    </p>
    <p>
      <img style="display: inline;" src="https://hypothes.is/organizations/__default__/logo" alt="Hypothesis">
      Adding an annotation using <a href="https://hypothes.is">hypothes.is</a>.
      To add an annotation, <span style="background-color: #3297FD; color: white">select some text</span> and then click the
      <span class="svg-icon--inline"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewbox="0 0 16 16" class="annotator-adder-actions__icon"><path fill="currentColor" fill-rule="nonzero" d="M15 0c.27 0 .505.099.703.297A.961.961 0 0116 1v15l-4-3H1a.974.974 0 01-.703-.29A.953.953 0 010 12V1C0 .719.096.482.29.29A.966.966 0 011 0h14zM7 3l-.469.063c-.312.041-.656.187-1.031.437-.375.25-.719.646-1.031 1.188C4.156 5.229 4 6 4 7l.002.063.006.062a.896.896 0 01.008.11l-.002.074-.006.066a1.447 1.447 0 00.43 1.188C4.729 8.854 5.082 9 5.5 9c.417 0 .77-.146 1.063-.438C6.854 8.271 7 7.918 7 7.5c0-.417-.146-.77-.438-1.063A1.447 1.447 0 005.5 6c-.073 0-.146.005-.219.016-.073.01-.14.026-.203.046.177-1.03.542-1.632 1.094-1.804L7 4V3zm5 0l-.469.063c-.312.041-.656.187-1.031.437-.375.25-.719.646-1.031 1.188C9.156 5.229 9 6 9 7l.002.063.006.062a.896.896 0 01.008.11l-.002.074-.006.066a1.447 1.447 0 00.43 1.188c.291.291.645.437 1.062.437.417 0 .77-.146 1.063-.438.291-.291.437-.645.437-1.062 0-.417-.146-.77-.438-1.063A1.447 1.447 0 0010.5 6c-.073 0-.146.005-.219.016-.073.01-.14.026-.203.046.177-1.03.542-1.632 1.094-1.804L12 4V3z"></path></svg></span>
      symbol on the pop-up menu.
      To see the annotations of others, click the
      <span class="svg-icon--inline"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewbox="0 0 16 16" class=""><g fill-rule="evenodd"><rect fill="none" stroke="none" x="0" y="0" width="16" height="16"></rect><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 12L6 8l4-4"></path></g></svg></span>
      symbol in the upper right-hand corner of the page.
    </p>
  </div>
</div>

<header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-baseRates" class="quarto-section-identifier"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Base Rates</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>This book is about learning statistics, prediction, and empiricism through the lens of fantasy football. It teaches readers how to use the free software R to perform fantasy football data analysis.</p>
  </div>
</div>


</header><section id="sec-baseRatesGettingStarted" class="level2" data-number="16.1"><h2 data-number="16.1" class="anchored" data-anchor-id="sec-baseRatesGettingStarted">
<span class="header-section-number">16.1</span> Getting Started</h2>
<section id="sec-baseRatesLoadPackages" class="level3" data-number="16.1.1"><h3 data-number="16.1.1" class="anchored" data-anchor-id="sec-baseRatesLoadPackages">
<span class="header-section-number">16.1.1</span> Load Packages</h3>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="fu">library</span>(<span class="st">"petersenlab"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section></section><section id="sec-baseRatesOverview" class="level2" data-number="16.2"><h2 data-number="16.2" class="anchored" data-anchor-id="sec-baseRatesOverview">
<span class="header-section-number">16.2</span> Overview</h2>
<p>Predicting player performance is a complex prediction task. Performance is probabilistically influenced by many processes, including processes internal to the player in addition to external processes. Moreover, people’s performance occurs in the context of a dynamic system with nonlinear, probabilistic, and cascading influences that change across time. The ever-changing system makes behavior challenging to predict. And, similar to chaos theory, one small change in the system can lead to large differences later on. Moreover, there are important factors to keep in mind when making predictions.</p>
<p>Let’s consider a prediction example, assuming the following probabilities:</p>
<ul>
<li>The probability of contracting HIV is .3%</li>
<li>The probability of a positive test for HIV is 1%</li>
<li>The probability of a positive test if you have HIV is 95%</li>
</ul>
<p>What is the probability of HIV if you have a positive test?</p>
<p>As we will see, the probability is: <span class="math inline">\(\frac{95\% \times .3\%}{1\%} = 28.5\%\)</span>. So based on the above probabilities, if you have a positive test, the probability that you have HIV is 28.5%. Most people tend to vastly overestimate the likelihood that the person has HIV in this example. Why? Because they do not pay enough attention to the base rate (in this example, the base rate of HIV is .3%).</p>
<p>In general, people tend to overestimate the likelihood of low base-rate events. That is, if the base rate of an event or condition—such as schizophrenia—is low (e.g., ~0.5%), people overestimate the likelihood that a person has schizophrenia when given specific information about the person such as their symptoms and history.</p>
</section><section id="sec-probability" class="level2" data-number="16.3"><h2 data-number="16.3" class="anchored" data-anchor-id="sec-probability">
<span class="header-section-number">16.3</span> Issues Around Probability</h2>
<section id="sec-probabilityTypes" class="level3" data-number="16.3.1"><h3 data-number="16.3.1" class="anchored" data-anchor-id="sec-probabilityTypes">
<span class="header-section-number">16.3.1</span> Types of Probabilities</h3>
<p>It is important to distinguish between different types of probabilities: marginal probabilities, joint probabilities, and conditional probabilities.</p>
<section id="sec-baseRate" class="level4" data-number="16.3.1.1"><h4 data-number="16.3.1.1" class="anchored" data-anchor-id="sec-baseRate">
<span class="header-section-number">16.3.1.1</span> Base Rate (Marginal Probability)</h4>
<p>The <em>base rate</em> is a marginal probability, which is the general probability of an event irrespective of other things. For instance, the base rate of HIV is the probability of developing HIV. In the U.S., <a href="https://map.aidsvu.org/profiles/nation/usa/overview">the prevalence rate of HIV is ~0.4% of the adult population</a> (archived at <a href="https://perma.cc/8GE6-GAPC" class="uri">https://perma.cc/8GE6-GAPC</a>).</p>
<p>For instance, we can consider the following marginal probabilities:</p>
<p><span class="math inline">\(P(C_i)\)</span> is the probability (i.e., base rate) of a classification, <span class="math inline">\(C\)</span>, independent of other things. A base rate is often used as the “<em>prior probability</em>” in a Bayesian model. In our example above, <span class="math inline">\(P(C_i)\)</span> is the base rate (i.e., prevalence) of HIV in the population: <span class="math inline">\(P(\text{HIV}) = .3\%\)</span>. <span class="math inline">\(P(R_i)\)</span> is the probability (base rate) of a response, <span class="math inline">\(R\)</span>, independent of other things. In the example above, <span class="math inline">\(P(R_i)\)</span> is the base rate of a positive test for HIV: <span class="math inline">\(P(\text{positive test}) = 1\%\)</span>. The base rate of a positive test is known as the <em>positivity rate</em> or <em>selection ratio</em>.</p>
</section><section id="sec-jointProbability" class="level4" data-number="16.3.1.2"><h4 data-number="16.3.1.2" class="anchored" data-anchor-id="sec-jointProbability">
<span class="header-section-number">16.3.1.2</span> Joint Probability</h4>
<p>A <em>joint probability</em> is the probability of two (or more) events occurring simultaneously. For instance, the probability of events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> both occurring together is <span class="math inline">\(P(A, B)\)</span>. A joint probability can be calculated using the <a href="#sec-baseRate">marginal probability</a> of each event, as in <a href="#eq-jointProbability" class="quarto-xref">Equation&nbsp;<span>16.1</span></a>:</p>
<p><span id="eq-jointProbability"><span class="math display">\[
P(A, B) = P(A) \cdot P(B)
\tag{16.1}\]</span></span></p>
<p>Conversely (and rearranging the terms for the calculation of <a href="#sec-conditionalProbability">conditional probability</a>), a <a href="#sec-jointProbability">joint probability</a> can also be calculated using the <a href="#sec-conditionalProbability">conditional probability</a> and <a href="#sec-baseRate">marginal probability</a>, as in <a href="#eq-jointProbability2" class="quarto-xref">Equation&nbsp;<span>16.2</span></a>:</p>
<p><span id="eq-jointProbability2"><span class="math display">\[
P(A, B) = P(A | B) \cdot P(B)
\tag{16.2}\]</span></span></p>
</section><section id="sec-conditionalProbability" class="level4" data-number="16.3.1.3"><h4 data-number="16.3.1.3" class="anchored" data-anchor-id="sec-conditionalProbability">
<span class="header-section-number">16.3.1.3</span> Conditional Probability</h4>
<p>A <em>conditional probability</em> is the probability of one event occurring given the occurrence of another event. Conditional probabilities are written as: <span class="math inline">\(P(A | B)\)</span>. This is read as the probability that event <span class="math inline">\(A\)</span> occurs given that event <span class="math inline">\(B\)</span> occurred. For instance, we can consider the following conditional probabilities:</p>
<p><span class="math inline">\(P(C | R)\)</span> is the probability of a classification, <span class="math inline">\(C\)</span>, given a response, <span class="math inline">\(R\)</span>. In other words, <span class="math inline">\(P(C | R)\)</span> is the probability of having HIV given a positive test: <span class="math inline">\(P(\text{HIV} | \text{positive test})\)</span>. <span class="math inline">\(P(R | C)\)</span> is the probability of a response, <span class="math inline">\(R\)</span>, given a classification, <span class="math inline">\(C\)</span>. In the example above, <span class="math inline">\(P(R | C)\)</span> is the probability of having a positive test given that a person has HIV: <span class="math inline">\(P(\text{positive test} | \text{HIV}) = 95\%\)</span>.</p>
<p>A conditional probability can be calculated using the <a href="#sec-jointProbability">joint probability</a> and <a href="#sec-baseRate">marginal probability</a> (base rate), as in <a href="#eq-conditionalProbability" class="quarto-xref">Equation&nbsp;<span>16.3</span></a>:</p>
<p><span id="eq-conditionalProbability"><span class="math display">\[
P(A, B) = P(A | B) \cdot P(B)
\tag{16.3}\]</span></span></p>
</section></section><section id="sec-inverseFallacy" class="level3" data-number="16.3.2"><h3 data-number="16.3.2" class="anchored" data-anchor-id="sec-inverseFallacy">
<span class="header-section-number">16.3.2</span> Confusion of the Inverse</h3>
<p>A <a href="#sec-conditionalProbability">conditional probability</a> is not the same thing as its reverse (or inverse) <a href="#sec-conditionalProbability">conditional probability</a>. Unless the <a href="#sec-baseRate">base rate</a> of the two events (<span class="math inline">\(C\)</span> and <span class="math inline">\(R\)</span>) are the same, <span class="math inline">\(P(C | R) \neq P(R | C)\)</span>. However, people frequently make the mistake of thinking that two inverse <a href="#sec-conditionalProbability">conditional probabilities</a> are the same. This mistake is known as the “confusion of the inverse”, or the “inverse fallacy”, or the “conditional probability fallacy”. The confusion of inverse probabilities is the logical error of representative thinking that leads people to assume that the probability of <span class="math inline">\(C\)</span> given <span class="math inline">\(R\)</span> is the same as the probability of <span class="math inline">\(R\)</span> given C, even though this is not true. As a few examples to demonstrate the logical fallacy, if 93% of breast cancers occur in high-risk women, this does not mean that 93% of high-risk women will eventually get breast cancer. As another example, if 77% of car accidents take place within 15 miles of a driver’s home, this does not mean that you will get in an accident 77% of times you drive within 15 miles of your home.</p>
<p>Which car is the most frequently stolen? It is often the Honda Accord or Honda Civic—probably because they are among the most popular/commonly available cars. The probability that the car is a Honda Accord given that a car was stolen (<span class="math inline">\(p(\text{Honda Accord } | \text{ Stolen})\)</span>) is what the media reports and what the police care about. However, that is not what buyers and car insurance companies should care about. Instead, they care about the probability that the car will be stolen given that it is a Honda Accord (<span class="math inline">\(p(\text{Stolen } | \text{ Honda Accord})\)</span>).</p>
<p>Applied to fantasy football, the probability that a given player will be injured given that he is a Running Back (<span class="math inline">\(p(\text{Injured } | \text{ RB})\)</span>) is not the same as the probability that a given player is a Running Back given that he is injured (<span class="math inline">\(p(\text{RB } | \text{ Injured})\)</span>).</p>
</section><section id="sec-bayesTheorem" class="level3" data-number="16.3.3"><h3 data-number="16.3.3" class="anchored" data-anchor-id="sec-bayesTheorem">
<span class="header-section-number">16.3.3</span> Bayes’ Theorem</h3>
<section id="sec-bayesTheoremStandard" class="level4" data-number="16.3.3.1"><h4 data-number="16.3.3.1" class="anchored" data-anchor-id="sec-bayesTheoremStandard">
<span class="header-section-number">16.3.3.1</span> Standard Formulation</h4>
<p>An alternative way of calculating a <a href="#sec-conditionalProbability">conditional probability</a> is using the inverse <a href="#sec-conditionalProbability">conditional probability</a> (instead of the <a href="#sec-jointProbability">joint probability</a>). This is known as Bayes’ theorem. Bayes’ theorem can help us calculate a <a href="#sec-conditionalProbability">conditional probability</a> of some classification, <span class="math inline">\(C\)</span>, given some response, <span class="math inline">\(R\)</span>, if we know the inverse <a href="#sec-conditionalProbability">conditional probability</a> and the <a href="#sec-baseRate">base rate</a> (marginal probability) of each. Bayes’ theorem is in <a href="#eq-bayes1" class="quarto-xref">Equation&nbsp;<span>16.4</span></a>:</p>
<p><span id="eq-bayes1"><span class="math display">\[
\begin{aligned}
  P(C | R) &amp;= \frac{P(R | C) \cdot P(C_i)}{P(R_i)}
\end{aligned}
\tag{16.4}\]</span></span></p>
<p>Or, equivalently (rearranging the terms):</p>
<p><span id="eq-bayes2"><span class="math display">\[
\begin{aligned}
  \frac{P(C | R)}{P(R | C)} = \frac{P(C_i)}{P(R_i)}
\end{aligned}
\tag{16.5}\]</span></span></p>
<p>Or, equivalently (rearranging the terms):</p>
<p><span id="eq-bayes3"><span class="math display">\[
\begin{aligned}
  \frac{P(C | R)}{P(C_i)} = \frac{P(R | C)}{P(R_i)}
\end{aligned}
\tag{16.6}\]</span></span></p>
<p>More generally, Bayes’ theorem has been described as:</p>
<p><span id="eq-bayes6"><span class="math display">\[
\begin{aligned}
  P(H | E) &amp;= \frac{P(E | H) \cdot P(H)}{P(E)} \\
  \text{posterior probability} &amp;= \frac{\text{likelihood} \times \text{prior probability}}{\text{model evidence}}
\end{aligned}
\tag{16.7}\]</span></span></p>
<p>where <span class="math inline">\(H\)</span> is the hypothesis, and <span class="math inline">\(E\)</span> is the evidence—the new information that was not used in computing the prior probability.</p>
<p>In Bayesian terms, the <em>posterior probability</em> is the conditional probability of one event occurring given another event—it is the updated probability after the evidence is considered. In this case, the posterior probability is the probability of the classification occurring (<span class="math inline">\(C\)</span>) given the response (<span class="math inline">\(R\)</span>). The <em>likelihood</em> is the inverse conditional probability—the probability of the response (<span class="math inline">\(R\)</span>) occurring given the classification (<span class="math inline">\(C\)</span>). The <em>prior probability</em> is the marginal probability of the event (i.e., the classification) occurring, before we take into account any new information. The <em>model evidence</em> is the marginal probability of the other event occurring—i.e., the marginal probability of seeing the evidence.</p>
<p>Bayes’ theorem provides the foundation for a paradigm of statistics called Bayesian statistics, which (unlike frequentist statistics) does not use <em>p</em>-values.</p>
<p>In the HIV example above, we can calculate the <a href="#sec-conditionalProbability">conditional probability</a> of HIV given a positive test using three terms: the <a href="#sec-conditionalProbability">conditional probability</a> of a positive test given HIV (i.e., the sensitivity of the test), the <a href="#sec-baseRate">base rate</a> of HIV, and the <a href="#sec-baseRate">base rate</a> of a positive test for HIV. The <a href="#sec-conditionalProbability">conditional probability</a> of HIV given a positive test is in <a href="#eq-hivExample1" class="quarto-xref">Equation&nbsp;<span>16.8</span></a>:</p>
<p><span id="eq-hivExample1"><span class="math display">\[
\begin{aligned}
  P(C | R) &amp;= \frac{P(R | C) \cdot P(C_i)}{P(R_i)} \\
  P(\text{HIV} | \text{positive test}) &amp;= \frac{P(\text{positive test} | \text{HIV}) \cdot P(\text{HIV})}{P(\text{positive test})} \\
  &amp;= \frac{\text{sensitivity of test} \times \text{base rate of HIV}}{\text{base rate of positive test}} \\
  &amp;= \frac{95\% \times .3\%}{1\%} = \frac{.95 \times .003}{.01}\\
  &amp;= 28.5\%
\end{aligned}
\tag{16.8}\]</span></span></p>
<p>The <a href="https://cran.r-project.org/web/packages/petersenlab/index.html"><code>petersenlab</code></a> package <span class="citation" data-cites="R-petersenlab">(<a href="references.html#ref-R-petersenlab" role="doc-biblioref">Petersen, 2024a</a>)</span> contains the <code>pAgivenB()</code> function that estimates the probability of one event, <span class="math inline">\(A\)</span>, given another event, <span class="math inline">\(B\)</span>.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>petersenlab<span class="sc">::</span><span class="fu">pAgivenB</span>(</span>
<span id="cb2-2"><a href="#cb2-2"></a>  <span class="at">pBgivenA =</span> .<span class="dv">95</span>,</span>
<span id="cb2-3"><a href="#cb2-3"></a>  <span class="at">pA =</span> .<span class="dv">003</span>,</span>
<span id="cb2-4"><a href="#cb2-4"></a>  <span class="at">pB =</span> .<span class="dv">01</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 0.285</code></pre>
</div>
</div>
<p>Thus, assuming the probabilities in the example above, the <a href="#conditionalProbability">conditional probability</a> of having HIV if a person has a positive test is 28.5%. Given a positive test, chances are higher than not that the person does not have HIV.</p>
<p>Now let’s see what happens if the person tests positive a second time. We would revise our “<a href="#sec-baseRate">prior probability</a>” for HIV from the general prevalence in the population (0.3%) to be the “posterior probability” of HIV given a first positive test (28.5%). This is known as <em>Bayesian updating</em>. We would also update the “evidence” to be the <a href="#sec-baseRate">marginal probability</a> of getting a second positive test.</p>
<p>If we do not know a <a href="#sec-baseRate">marginal probability</a> (i.e., base rate) of an event (e.g., getting a second positive test), we can calculate a <a href="#sec-baseRate">marginal probability</a> with the <em>law of total probability</em> using <a href="#sec-conditionalProbability">conditional probabilities</a> and the <a href="#sec-baseRate">marginal probability</a> of another event (e.g., having HIV). According to the law of total probability, the probability of getting a positive test is the probability that a person with HIV gets a positive test (i.e., sensitivity) times the base rate of HIV plus the probability that a person without HIV gets a positive test (i.e., false positive rate) times the <a href="#sec-baseRate">base rate</a> of not having HIV, as in <a href="#eq-lawOfTotalProbability" class="quarto-xref">Equation&nbsp;<span>16.9</span></a>:</p>
<p><span id="eq-lawOfTotalProbability"><span class="math display">\[
\begin{aligned}
P(\text{not } C_i) &amp;= 1 - P(C_i) \\
  P(R_i) &amp;= P(R | C) \cdot P(C_i) + P(R | \text{not } C) \cdot P(\text{not } C_i) \\
  1\% &amp;= 95\% \times .3\% + P(R | \text{not } C) \times 99.7\% \\
\end{aligned}
\tag{16.9}\]</span></span></p>
<p>In this case, we know the <a href="#sec-baseRate">marginal probability</a> (<span class="math inline">\(P(R_i)\)</span>), and we can use that to solve for the unknown <a href="#sec-conditionalProbability">conditional probability</a> that reflects the false positive rate (<span class="math inline">\(P(R | \text{not } C)\)</span>), as in <a href="#eq-conditionalProbabilityRevised" class="quarto-xref">Equation&nbsp;<span>16.10</span></a>:</p>
<p><span id="eq-conditionalProbabilityRevised"><span class="math display">\[
\scriptsize
\begin{aligned}
  P(R_i) &amp;= P(R | C) \cdot P(C_i) + P(R | \text{not } C) \cdot P(\text{not } C_i) &amp;&amp; \\
  P(R_i) - [P(R | \text{not } C) \cdot P(\text{not } C_i)] &amp;= P(R | C) \cdot P(C_i) &amp;&amp; \text{Move } P(R | \text{not } C) \text{ to the left side} \\
  - [P(R | \text{not } C) \cdot P(\text{not } C_i)] &amp;= P(R | C) \cdot P(C_i) - P(R_i) &amp;&amp; \text{Move } P(R_i) \text{ to the right side} \\
  P(R | \text{not } C) \cdot P(\text{not } C_i) &amp;= P(R_i) - [P(R | C) \cdot P(C_i)] &amp;&amp; \text{Multiply by } -1 \\
  P(R | \text{not } C) &amp;= \frac{P(R_i) - [P(R | C) \cdot P(C_i)]}{P(\text{not } C_i)} &amp;&amp; \text{Divide by } P(R | \text{not } C) \\
  &amp;= \frac{1\% - [95\% \times .3\%]}{99.7\%} = \frac{.01 - [.95 \times .003]}{.997}\\
  &amp;= .7171515\% \\
\end{aligned}
\tag{16.10}\]</span></span></p>
<p>We can then estimate the marginal probability of the event, substititing in <span class="math inline">\(P(R | \text{not } C)\)</span>, using the law of total probability. The <a href="https://cran.r-project.org/web/packages/petersenlab/index.html"><code>petersenlab</code></a> package <span class="citation" data-cites="R-petersenlab">(<a href="references.html#ref-R-petersenlab" role="doc-biblioref">Petersen, 2024a</a>)</span> contains the <code>pA()</code> function that estimates the marginal probability of one event, <span class="math inline">\(A\)</span>.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a>petersenlab<span class="sc">::</span><span class="fu">pA</span>(</span>
<span id="cb4-2"><a href="#cb4-2"></a>  <span class="at">pAgivenB =</span> .<span class="dv">95</span>,</span>
<span id="cb4-3"><a href="#cb4-3"></a>  <span class="at">pB =</span> .<span class="dv">003</span>,</span>
<span id="cb4-4"><a href="#cb4-4"></a>  <span class="at">pAgivenNotB =</span> .<span class="dv">007171515</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01</code></pre>
</div>
</div>
<p>The <a href="https://cran.r-project.org/web/packages/petersenlab/index.html"><code>petersenlab</code></a> package <span class="citation" data-cites="R-petersenlab">(<a href="references.html#ref-R-petersenlab" role="doc-biblioref">Petersen, 2024a</a>)</span> contains the <code>pBgivenNotA()</code> function that estimates the probability of one event, <span class="math inline">\(B\)</span>, given that another event, <span class="math inline">\(A\)</span>, did not occur.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>petersenlab<span class="sc">::</span><span class="fu">pBgivenNotA</span>(</span>
<span id="cb6-2"><a href="#cb6-2"></a>  <span class="at">pBgivenA =</span> .<span class="dv">95</span>,</span>
<span id="cb6-3"><a href="#cb6-3"></a>  <span class="at">pA =</span> .<span class="dv">003</span>,</span>
<span id="cb6-4"><a href="#cb6-4"></a>  <span class="at">pB =</span> .<span class="dv">01</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 0.007171515</code></pre>
</div>
</div>
<p>With this <a href="#sec-conditionalProbability">conditional probability</a> (<span class="math inline">\(P(R | \text{not } C)\)</span>), the updated <a href="#sec-baseRate">marginal probability</a> of having HIV (<span class="math inline">\(P(C_i)\)</span>), and the updated marginal probability of not having HIV (<span class="math inline">\(P(\text{not } C_i)\)</span>), we can now calculate an updated estimate of the <a href="#sec-baseRate">marginal probability</a> of getting a second positive test. The probability of getting a second positive test is the probability that a person with HIV gets a second positive test (i.e., sensitivity) times the updated probability of HIV plus the probability that a person without HIV gets a second positive test (i.e., false positive rate) times the updated probability of not having HIV, as in <a href="#eq-baseRateUpdated" class="quarto-xref">Equation&nbsp;<span>16.11</span></a>:</p>
<p><span id="eq-baseRateUpdated"><span class="math display">\[
\begin{aligned}
  P(R_{i}) &amp;= P(R | C) \cdot P(C_i) + P(R | \text{not } C) \cdot P(\text{not } C_i) \\
  &amp;= 95\% \times 28.5\% + .7171515\% \times 71.5\% = .95 \times .285 + .007171515 \times .715 \\
  &amp;= 27.58776\%
\end{aligned}
\tag{16.11}\]</span></span></p>
<p>The <a href="https://cran.r-project.org/web/packages/petersenlab/index.html"><code>petersenlab</code></a> package <span class="citation" data-cites="R-petersenlab">(<a href="references.html#ref-R-petersenlab" role="doc-biblioref">Petersen, 2024a</a>)</span> contains the <code>pB()</code> function that estimates the marginal probability of one event, <span class="math inline">\(B\)</span>.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>petersenlab<span class="sc">::</span><span class="fu">pB</span>(</span>
<span id="cb8-2"><a href="#cb8-2"></a>  <span class="at">pBgivenA =</span> .<span class="dv">95</span>,</span>
<span id="cb8-3"><a href="#cb8-3"></a>  <span class="at">pA =</span> .<span class="dv">285</span>,</span>
<span id="cb8-4"><a href="#cb8-4"></a>  <span class="at">pBgivenNotA =</span> .<span class="dv">007171515</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2758776</code></pre>
</div>
</div>
<p>We then substitute the updated <a href="#sec-baseRate">marginal probability</a> of HIV (<span class="math inline">\(P(C_i)\)</span>) and the updated <a href="#sec-baseRate">marginal probability</a> of getting a second positive test (<span class="math inline">\(P(R_i)\)</span>) into Bayes’ theorem to get the probability that the person has HIV if they have a second positive test (assuming the errors of each test are independent, i.e., uncorrelated), as in <a href="#eq-baseRateUpdated2" class="quarto-xref">Equation&nbsp;<span>16.12</span></a>:</p>
<p><span id="eq-baseRateUpdated2"><span class="math display">\[
\begin{aligned}
  P(C | R) &amp;= \frac{P(R | C) \cdot P(C_i)}{P(R_i)} \\
  P(\text{HIV} | \text{a second positive test}) &amp;= \frac{P(\text{a second positive test} | \text{HIV}) \cdot P(\text{HIV})}{P(\text{a second positive test})} \\
  &amp;= \frac{\text{sensitivity of test} \times \text{updated base rate of HIV}}{\text{updated base rate of positive test}} \\
  &amp;= \frac{95\% \times 28.5\%}{27.58776\%} \\
  &amp;= 98.14\%
\end{aligned}
\tag{16.12}\]</span></span></p>
<p>The <a href="https://cran.r-project.org/web/packages/petersenlab/index.html"><code>petersenlab</code></a> package <span class="citation" data-cites="R-petersenlab">(<a href="references.html#ref-R-petersenlab" role="doc-biblioref">Petersen, 2024a</a>)</span> contains the <code>pAgivenB()</code> function that estimates the probability of one event, <span class="math inline">\(A\)</span>, given another event, <span class="math inline">\(B\)</span>.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a>petersenlab<span class="sc">::</span><span class="fu">pAgivenB</span>(</span>
<span id="cb10-2"><a href="#cb10-2"></a>  <span class="at">pBgivenA =</span> .<span class="dv">95</span>,</span>
<span id="cb10-3"><a href="#cb10-3"></a>  <span class="at">pA =</span> .<span class="dv">285</span>,</span>
<span id="cb10-4"><a href="#cb10-4"></a>  <span class="at">pB =</span> .<span class="dv">2758776</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9814135</code></pre>
</div>
</div>
<p>Thus, a second positive test greatly increases the posterior probability that the person has HIV from 28.5% to over 98%.</p>
<p>As seen in the rearranged formula in <a href="#eq-bayes2" class="quarto-xref">Equation&nbsp;<span>16.5</span></a>, the ratio of the <a href="#sec-conditionalProbability">conditional probabilities</a> is equal to the ratio of the <a href="#sec-baseRate">base rates</a>. Thus, it is important to consider <a href="#sec-baseRate">base rates</a>. People have a strong tendency to ignore (or give insufficient weight to) <a href="#sec-baseRate">base rates</a> when making predictions. The failure to consider the <a href="#sec-baseRate">base rate</a> when making predictions when given specific information about a case is known as the <a href="cognitive-bias.html#sec-fallaciesBaseRate">base rate fallacy</a> or as <a href="cognitive-bias.html#sec-fallaciesBaseRate">base rate neglect</a>. For example, people tend to say that the probability of a rare event is more likely than it actually is given specific information.</p>
<p>As seen in the rearranged formula in <a href="#eq-bayes3" class="quarto-xref">Equation&nbsp;<span>16.6</span></a>, the inverse <a href="#sec-conditionalProbability">conditional probabilities</a> (<span class="math inline">\(P(C | R)\)</span> and <span class="math inline">\(P(R | C)\)</span>) are not equal unless the <a href="#sec-baseRate">base rates</a> of <span class="math inline">\(C\)</span> and <span class="math inline">\(R\)</span> are the same. If the <a href="#sec-baseRate">base rates</a> are not equal, we are making at least some prediction errors. If <span class="math inline">\(P(C_i) &gt; P(R_i)\)</span>, our predictions must include some false negatives. If <span class="math inline">\(P(R_i) &gt; P(C_i)\)</span>, our predictions must include some false positives.</p>
</section><section id="sec-bayesTheoremAlternative" class="level4" data-number="16.3.3.2"><h4 data-number="16.3.3.2" class="anchored" data-anchor-id="sec-bayesTheoremAlternative">
<span class="header-section-number">16.3.3.2</span> Alternative Formulation</h4>
<p>Using the law of total probability, we can substitute the calculation of the <a href="#sec-baseRate">marginal probability</a> (<span class="math inline">\(P(R_i)\)</span>) into Bayes’ theorem to get an alternative formulation of Bayes’ theorem, as in <a href="#eq-baseRateUpdated3" class="quarto-xref">Equation&nbsp;<span>16.13</span></a>:</p>
<p><span id="eq-baseRateUpdated3"><span class="math display">\[
\begin{aligned}
  P(C | R) &amp;= \frac{P(R | C) \cdot P(C_i)}{P(R_i)} \\
  &amp;= \frac{P(R | C) \cdot P(C_i)}{P(R | C) \cdot P(C_i) + P(R | \text{not } C) \cdot P(\text{not } C_i)} \\
  &amp;= \frac{P(R | C) \cdot P(C_i)}{P(R | C) \cdot P(C_i) + P(R | \text{not } C) \cdot [1 - P(C_i)]}
\end{aligned}
\tag{16.13}\]</span></span></p>
<p>Instead of using <a href="#sec-baseRate">marginal probability</a> (<a href="#sec-baseRate">base rate</a>) of <span class="math inline">\(R\)</span>, as in the original formulation of Bayes’ theorem, it uses the <a href="#sec-conditionalProbability">conditional probability</a>, <span class="math inline">\(P(R|\text{not } C)\)</span>. Thus, it uses three terms: two <a href="#sec-conditionalProbability">conditional probabilities</a>—<span class="math inline">\(P(R|C)\)</span> and <span class="math inline">\(P(R|\text{not } C)\)</span>—and one <a href="#sec-baseRate">marginal probability</a>, <span class="math inline">\(P(C_i)\)</span>.</p>
<p>Let us see how the alternative formulation of Bayes’ theorem applies to the HIV example above. We can calculate the probability of HIV given a positive test using three terms: the <a href="#sec-conditionalProbability">conditional probability</a> that a person with HIV gets a positive test (i.e., <a href="evaluating-prediction-accuracy.html#sec-sensitivity">sensitivity</a>), the <a href="#sec-conditionalProbability">conditional probability</a> that a person without HIV gets a positive test (i.e., <a href="evaluating-prediction-accuracy.html#sec-falsePositiveRate">false positive rate</a>), and the <a href="#sec-baseRate">base rate</a> of HIV. Using the <span class="math inline">\(P(R|\text{not } C)\)</span> calculated in <a href="#eq-conditionalProbabilityRevised" class="quarto-xref">Equation&nbsp;<span>16.10</span></a>, the <a href="#sec-conditionalProbability">conditional probability</a> of HIV given a single positive test is in <a href="#eq-bayes4" class="quarto-xref">Equation&nbsp;<span>16.14</span></a>:</p>
<p><span id="eq-bayes4"><span class="math display">\[
\small
\begin{aligned}
  P(C | R) &amp;= \frac{P(R | C) \cdot P(C_i)}{P(R | C) \cdot P(C_i) + P(R | \text{not } C) \cdot [1 - P(C_i)]} \\
  &amp;= \frac{\text{sensitivity of test} \times \text{base rate of HIV}}{\text{sensitivity of test} \times \text{base rate of HIV} + \text{false positive rate of test} \times (1 - \text{base rate of HIV})} \\
  &amp;= \frac{95\% \times .3\%}{95\% \times .3\% + .7171515\% \times (1 - .3\%)} = \frac{.95 \times .003}{.95 \times .003 + .007171515 \times (1 - .003)}\\
  &amp;= 28.5\%
\end{aligned}
\tag{16.14}\]</span></span></p>
<p>The <a href="https://cran.r-project.org/web/packages/petersenlab/index.html"><code>petersenlab</code></a> package <span class="citation" data-cites="R-petersenlab">(<a href="references.html#ref-R-petersenlab" role="doc-biblioref">Petersen, 2024a</a>)</span> contains the <code>pAgivenB()</code> function that estimates the probability of one event, <span class="math inline">\(A\)</span>, given another event, <span class="math inline">\(B\)</span>.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="fu">pAgivenB</span>(</span>
<span id="cb12-2"><a href="#cb12-2"></a>  <span class="at">pBgivenA =</span> .<span class="dv">95</span>,</span>
<span id="cb12-3"><a href="#cb12-3"></a>  <span class="at">pA =</span> .<span class="dv">003</span>,</span>
<span id="cb12-4"><a href="#cb12-4"></a>  <span class="at">pBgivenNotA =</span> .<span class="dv">007171515</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 0.285</code></pre>
</div>
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a><span class="fu">pAgivenB</span>(</span>
<span id="cb14-2"><a href="#cb14-2"></a>  <span class="at">pBgivenA =</span> .<span class="dv">95</span>,</span>
<span id="cb14-3"><a href="#cb14-3"></a>  <span class="at">pA =</span> .<span class="dv">003</span>,</span>
<span id="cb14-4"><a href="#cb14-4"></a>  <span class="at">pBgivenNotA =</span> <span class="fu">pBgivenNotA</span>(</span>
<span id="cb14-5"><a href="#cb14-5"></a>    <span class="at">pBgivenA =</span> .<span class="dv">95</span>,</span>
<span id="cb14-6"><a href="#cb14-6"></a>    <span class="at">pA =</span> .<span class="dv">003</span>,</span>
<span id="cb14-7"><a href="#cb14-7"></a>    <span class="at">pB =</span> .<span class="dv">01</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 0.285</code></pre>
</div>
</div>
<p>To calculate the <a href="#sec-conditionalProbability">conditional probability</a> of HIV given a second positive test, we update our priors because the person has now tested positive for HIV. We update the <a href="#sec-baseRate">prior probability</a> of HIV (<span class="math inline">\(P(C_i)\)</span>) based on the posterior probability of HIV after a positive test (<span class="math inline">\(P(C | R)\)</span>) that we calculated above. We can calculate the <a href="#sec-conditionalProbability">conditional probability</a> of HIV given a second positive test using three terms: the <a href="#sec-conditionalProbability">conditional probability</a> that a person with HIV gets a positive test (i.e., <a href="evaluating-prediction-accuracy.html#sec-sensitivity">sensitivity</a>; which stays the same), the <a href="#sec-conditionalProbability">conditional probability</a> that a person without HIV gets a positive test (i.e., <a href="evaluating-prediction-accuracy.html#sec-falsePositiveRate">false positive rate</a>; which stays the same), and the updated <a href="#sec-baseRate">marginal probability</a> of HIV. The <a href="#sec-conditionalProbability">conditional probability</a> of HIV given a second positive test is in <a href="#eq-baseRateUpdated4" class="quarto-xref">Equation&nbsp;<span>16.15</span></a>:</p>
<p><span id="eq-baseRateUpdated4"><span class="math display">\[
\scriptsize
\begin{aligned}
  P(C | R) &amp;= \frac{P(R | C) \cdot P(C_i)}{P(R | C) \cdot P(C_i) + P(R | \text{not } C) \cdot [1 - P(C_i)]} \\
  &amp;= \frac{\text{sensitivity of test} \times \text{updated base rate of HIV}}{\text{sensitivity of test} \times \text{updated base rate of HIV} + \text{false positive rate of test} \times (1 - \text{updated base rate of HIV})} \\
  &amp;= \frac{95\% \times 28.5\%}{95\% \times 28.5\% + .7171515\% \times (1 - 28.5\%)} = \frac{.95 \times .285}{.95 \times .285 + .007171515 \times (1 - .285)}\\
  &amp;= 98.14\%
\end{aligned}
\tag{16.15}\]</span></span></p>
<p>The <a href="https://cran.r-project.org/web/packages/petersenlab/index.html"><code>petersenlab</code></a> package <span class="citation" data-cites="R-petersenlab">(<a href="references.html#ref-R-petersenlab" role="doc-biblioref">Petersen, 2024a</a>)</span> contains the <code>pAgivenB()</code> function that estimates the probability of one event, <span class="math inline">\(A\)</span>, given another event, <span class="math inline">\(B\)</span>.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="fu">pAgivenB</span>(</span>
<span id="cb16-2"><a href="#cb16-2"></a>  <span class="at">pBgivenA =</span> .<span class="dv">95</span>,</span>
<span id="cb16-3"><a href="#cb16-3"></a>  <span class="at">pA =</span> .<span class="dv">285</span>,</span>
<span id="cb16-4"><a href="#cb16-4"></a>  <span class="at">pBgivenNotA =</span> .<span class="dv">007171515</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9814134</code></pre>
</div>
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="fu">pAgivenB</span>(</span>
<span id="cb18-2"><a href="#cb18-2"></a>  <span class="at">pBgivenA =</span> .<span class="dv">95</span>,</span>
<span id="cb18-3"><a href="#cb18-3"></a>  <span class="at">pA =</span> .<span class="dv">285</span>,</span>
<span id="cb18-4"><a href="#cb18-4"></a>  <span class="at">pBgivenNotA =</span> <span class="fu">pBgivenNotA</span>(</span>
<span id="cb18-5"><a href="#cb18-5"></a>    <span class="at">pBgivenA =</span> .<span class="dv">95</span>,</span>
<span id="cb18-6"><a href="#cb18-6"></a>    <span class="at">pA =</span> .<span class="dv">003</span>,</span>
<span id="cb18-7"><a href="#cb18-7"></a>    <span class="at">pB =</span> .<span class="dv">01</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9814134</code></pre>
</div>
</div>
</section><section id="interim-summary" class="level4" data-number="16.3.3.3"><h4 data-number="16.3.3.3" class="anchored" data-anchor-id="interim-summary">
<span class="header-section-number">16.3.3.3</span> Interim Summary</h4>
<p>In sum, the <a href="#sec-baseRate">marginal probability</a>, including the <a href="#sec-baseRate">prior probability</a> or <a href="#sec-baseRate">base rate</a>, should be weighed heavily in predictions unless there are sufficient data to indicate otherwise, i.e., to update the posterior probability based on new evidence. Bayes’ theorem specifies how prior beliefs (i.e., <a href="#sec-baseRate">base rate</a> informations) should be integrated with the <a href="research-methods.html#sec-predictiveValidity">predictive accuracy</a> of the evidence to make predictions. It thus provides a powerful tool to <a href="cognitive-bias.html#sec-heuristicsAnchoringAdjustment">anchor</a> predictions to the <a href="#sec-baseRate">base rate</a> unless sufficient evidence changes the posterior probability (by updating the evidence and <a href="#sec-baseRate">prior probability</a>). In general, you should <a href="cognitive-bias.html#sec-heuristicsAnchoringAdjustment">anchor</a> your predictions to the <a href="#sec-baseRate">base rate</a> and <a href="cognitive-bias.html#sec-heuristicsAnchoringAdjustment">adjust</a> from there. As noted by <span class="citation" data-cites="Kahneman2011">Kahneman (<a href="references.html#ref-Kahneman2011" role="doc-biblioref">2011</a>)</span>, if you have doubts about the quality of the evidence for a particular prediction question, keep your predictions close to the <a href="#sec-baseRate">base rate</a>, and modify them only modifying them based on the new information.</p>
</section></section></section><section id="sec-cabExample" class="level2" data-number="16.4"><h2 data-number="16.4" class="anchored" data-anchor-id="sec-cabExample">
<span class="header-section-number">16.4</span> Cab Example</h2>
<p>Below is an example:</p>
<blockquote class="blockquote">
<p>A cab was involved in a hit-and-run accident at night. Two cab companies, the Green and the Blue, operate in the city. You are given the following data:</p>
<ul>
<li>85% of the cabs in the city are Green and 15% are Blue.</li>
<li>A witness identified the cab as Blue. The court tested the reliability of the witness under the circumstances that existed on the night of the accident and concluded that the witness correctly identified each one of the two colors 80% of the time and failed 20% of the time.</li>
</ul>
<p>What is the probability that the cab involved in the accident was Blue rather than Green?</p>
<p>— Kahneman <span class="citation" data-cites="Kahneman2011">(<a href="references.html#ref-Kahneman2011" role="doc-biblioref">2011, p. 166</a>)</span></p>
</blockquote>
<p>Thus, we know the following:</p>
<p><span id="eq-cabExampleGivenInfo"><span class="math display">\[
\begin{aligned}
  P(\text{Blue}) &amp;= .15 &amp;&amp; \text{prior probability of a Blue cab}\\
  P(\text{Green}) &amp;= .85 &amp;&amp; \text{prior probability of a Green cab}\\
  P(\text{Correct}|\text{Blue}) &amp;= .80 &amp;&amp; \text{probability the witness correctly identifies a Blue cab}\\
  P(\text{Correct}|\text{Green}) &amp;= .80 &amp;&amp; \text{probability the witness correctly identifies a Green cab}\\
  P(\text{Incorrect}|\text{Blue}) &amp;= .20 &amp;&amp; \text{probability the witness incorrectly identifies a Blue cab}\\
  P(\text{Incorrect}|\text{Green}) &amp;= .20 &amp;&amp; \text{probability the witness incorrectly identifies a Green cab}\\
\end{aligned}
\tag{16.16}\]</span></span></p>
<p>We want to know the probability that the cab involved in the accident was Blue, given that the witness identified it as Blue (<span class="math inline">\(P(\text{Blue}|\text{Identified as Blue})\)</span>). To estimate this probability, we can apply <a href="#sec-bayesTheorem">Bayes’ theorem</a> to estimate the posterior probability:</p>
<p><span id="eq-cabExampleBayesTheorem"><span class="math display">\[
\begin{aligned}
  P(C | R) &amp;= \frac{P(R | C) \cdot P(C_i)}{P(R_i)}\\
  P(\text{Blue}|\text{Identified as Blue}) &amp;= \frac{P(\text{Identified as Blue}|\text{Blue}) \cdot P(\text{Blue})}{P(\text{Identified as Blue})}
\end{aligned}
\tag{16.17}\]</span></span></p>
<p>We can compute the term in the denominator (<span class="math inline">\(P(\text{Identified as Blue})\)</span>) using the law of total probability (described in <a href="#sec-bayesTheorem" class="quarto-xref"><span>Section 16.3.3</span></a>).</p>
<p><span id="eq-cabExampleLawOfTotalProbability"><span class="math display">\[
\begin{aligned}
  P(R_i) &amp;= P(R | C) \cdot P(C_i) + P(R | \text{not } C) \cdot P(\text{not } C_i)\\
  P(R_i) &amp;= P(\text{Identified as Blue}|\text{Blue}) \cdot P(\text{Blue}) + P(\text{Identified as Blue}|\text{Green}) \cdot P(\text{Green})\\
  0.29 &amp;= (.80 \times .15) + (.20 \times .85) \\
\end{aligned}
\tag{16.18}\]</span></span></p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a>petersenlab<span class="sc">::</span><span class="fu">pA</span>(</span>
<span id="cb20-2"><a href="#cb20-2"></a>  <span class="at">pAgivenB =</span> .<span class="dv">80</span>,</span>
<span id="cb20-3"><a href="#cb20-3"></a>  <span class="at">pB =</span> .<span class="dv">15</span>,</span>
<span id="cb20-4"><a href="#cb20-4"></a>  <span class="at">pAgivenNotB =</span> .<span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 0.29</code></pre>
</div>
</div>
<p>We can now substitute this value into the denominator of Bayes’ theorem to estimate the posterior probability:</p>
<p><span id="eq-cabExamplePosterior"><span class="math display">\[
\begin{aligned}
  P(C | R) &amp;= \frac{P(R | C) \cdot P(C_i)}{P(R_i)}\\
  P(\text{Blue}|\text{Identified as Blue}) &amp;= \frac{P(\text{Identified as Blue}|\text{Blue}) \cdot P(\text{Blue})}{P(\text{Identified as Blue})}\\
  0.414 &amp;= \frac{0.80 \times 0.15}{0.29}
\end{aligned}
\tag{16.19}\]</span></span></p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a>petersenlab<span class="sc">::</span><span class="fu">pAgivenB</span>(</span>
<span id="cb22-2"><a href="#cb22-2"></a>  <span class="at">pBgivenA =</span> .<span class="dv">80</span>,</span>
<span id="cb22-3"><a href="#cb22-3"></a>  <span class="at">pA =</span> .<span class="dv">15</span>,</span>
<span id="cb22-4"><a href="#cb22-4"></a>  <span class="at">pB =</span> .<span class="dv">29</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4137931</code></pre>
</div>
</div>
<p>Thus, there was a 41.4% probability that the car involved in the accident was Blue rather than Green. However, when faced with this problem, people tend to <a href="cognitive-bias.html#sec-fallaciesBaseRate">ignore the base rate</a> and go with the witness <span class="citation" data-cites="Kahneman2011">(<a href="references.html#ref-Kahneman2011" role="doc-biblioref">Kahneman, 2011</a>)</span>. According to <span class="citation" data-cites="Kahneman2011">Kahneman (<a href="references.html#ref-Kahneman2011" role="doc-biblioref">2011</a>)</span>, the most frequent response to this question regarding is that there is an 80% that the car was Blue.</p>
</section><section id="sec-nateSilverExamples" class="level2" data-number="16.5"><h2 data-number="16.5" class="anchored" data-anchor-id="sec-nateSilverExamples">
<span class="header-section-number">16.5</span> Nate Silver Examples</h2>
<p><span class="citation" data-cites="Silver2012">Silver (<a href="references.html#ref-Silver2012" role="doc-biblioref">2012</a>)</span> provides several examples that leverage the <a href="#sec-bayesTheoremAlternative">alternative formulation of Bayes’ theorem</a> provided in <a href="#eq-baseRateUpdated3" class="quarto-xref">Equation&nbsp;<span>16.13</span></a> and summarized below:</p>
<p><span id="eq-baseRateAlternative"><span class="math display">\[
\begin{aligned}
  P(C | R) &amp;= \frac{P(R | C) \cdot P(C_i)}{P(R | C) \cdot P(C_i) + P(R | \text{not } C) \cdot [1 - P(C_i)]}
\end{aligned}
\tag{16.20}\]</span></span></p>
<p>In each example, the formula uses three elements to calculate the probability that the hypothesis is true:</p>
<ol type="1">
<li>the <a href="#sec-conditionalProbability">conditional probability</a> the likelihood of observing the evidence, <span class="math inline">\(R\)</span>, given that the hypothesis, <span class="math inline">\(C\)</span>, is true (i.e., <span class="math inline">\(P(R|C)\)</span>; <a href="evaluating-prediction-accuracy.html#sec-sensitivity">true positive rate</a>)</li>
<li>the <a href="#sec-conditionalProbability">conditional probability</a> the likelihood of observing the evidence, <span class="math inline">\(R\)</span>, given that the hypothesis, <span class="math inline">\(C\)</span>, is false (i.e., <span class="math inline">\(P(R | \text{not } C)\)</span>; <a href="evaluating-prediction-accuracy.html#sec-falsePositiveRate">false positive rate</a>)</li>
<li>the <a href="#sec-baseRate">marginal probability</a> (base rate) of the event occurring (i.e., the prior probability of the hypothesis, <span class="math inline">\(C\)</span>, being true; <span class="math inline">\(P(C_i)\)</span>)</li>
</ol>
<p>Thus, the formula uses the <a href="#sec-baseRate">base rate</a>, the <a href="evaluating-prediction-accuracy.html#sec-sensitivity">true positive rate</a> (sensitivity), and the <a href="evaluating-prediction-accuracy.html#sec-falsePositiveRate">false positive rate</a>. The ratio of the <a href="evaluating-prediction-accuracy.html#sec-sensitivity">true positive rate</a> to the <a href="evaluating-prediction-accuracy.html#sec-falsePositiveRate">false positive rate</a> is called the <a href="#sec-positiveLikelihoodRatio">positive likelihood ratio</a>, and is used in <a href="#sec-bayesianUpdating">Bayesian updating</a>.</p>
<section id="sec-nateSilverExample1" class="level3" data-number="16.5.1"><h3 data-number="16.5.1" class="anchored" data-anchor-id="sec-nateSilverExample1">
<span class="header-section-number">16.5.1</span> Example 1: Is Your Partner Cheating on You?</h3>
<p>Example 1: You came home and found a strange pair of underwear in your underwear drawer. What is the probability that your partner is cheating on you?</p>
<ul>
<li>the <a href="#sec-baseRate">prior probability</a> that your partner is cheating on you: 4%</li>
<li>the <a href="#sec-conditionalProbability">conditional probability</a> of underwear appearing given that your partner is cheating on you: 50%</li>
<li>the <a href="#sec-conditionalProbability">conditional probability</a> of underwear appearing given that your partner is <em>not</em> cheating on you: 5%</li>
</ul>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="fu">pAgivenB</span>(</span>
<span id="cb24-2"><a href="#cb24-2"></a>  <span class="at">pBgivenA =</span> .<span class="dv">50</span>,</span>
<span id="cb24-3"><a href="#cb24-3"></a>  <span class="at">pA =</span> .<span class="dv">04</span>,</span>
<span id="cb24-4"><a href="#cb24-4"></a>  <span class="at">pBgivenNotA =</span> .<span class="dv">05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2941176</code></pre>
</div>
</div>
</section><section id="sec-nateSilverExample2" class="level3" data-number="16.5.2"><h3 data-number="16.5.2" class="anchored" data-anchor-id="sec-nateSilverExample2">
<span class="header-section-number">16.5.2</span> Example 2: Does a Person Have Breast Cancer?</h3>
<p>Example 2: What is the probability that a woman in her 40s has breast cancer if she tested positive on a mammogram?</p>
<ul>
<li>the <a href="#sec-baseRate">prior probability</a> that she has breast cancer: 1.4%</li>
<li>the <a href="#sec-conditionalProbability">conditional probability</a> that she has a positive test given that she has breast cancer: 75%</li>
<li>the <a href="#sec-conditionalProbability">conditional probability</a> that she has a positive test given that she does <em>not</em> have breast cancer: 10%</li>
</ul>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="fu">pAgivenB</span>(</span>
<span id="cb26-2"><a href="#cb26-2"></a>  <span class="at">pBgivenA =</span> .<span class="dv">75</span>,</span>
<span id="cb26-3"><a href="#cb26-3"></a>  <span class="at">pA =</span> .<span class="dv">014</span>,</span>
<span id="cb26-4"><a href="#cb26-4"></a>  <span class="at">pBgivenNotA =</span> .<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 0.09624198</code></pre>
</div>
</div>
</section><section id="sec-nateSilverExample3" class="level3" data-number="16.5.3"><h3 data-number="16.5.3" class="anchored" data-anchor-id="sec-nateSilverExample3">
<span class="header-section-number">16.5.3</span> Example 3: Was it a Terrorist Attack?</h3>
<section id="sec-nateSilverExample3A" class="level4" data-number="16.5.3.1"><h4 data-number="16.5.3.1" class="anchored" data-anchor-id="sec-nateSilverExample3A">
<span class="header-section-number">16.5.3.1</span> Example 3A: The First Plane Hit the World Trade Center</h4>
<p>Example 3A: Consider the information we had on 9/11 when the first plane hit the World Trade Center. What is the probability that a terror attack occurred given that the first plane hit the World Trade Center?</p>
<ul>
<li>the <a href="#sec-baseRate">prior probability</a> that terrorists crash a plane into a Manhattan skyscraper: 0.005%</li>
<li>the <a href="#sec-conditionalProbability">conditional probability</a> that a plane crashes into a Manhattan skyscraper if terrorists are attacking Manhattan skyscrapers: 100%</li>
<li>the <a href="#sec-conditionalProbability">conditional probability</a> that a plane crashes into a Manhattan skyscraper if terrorists are <em>not</em> attacking Manhattan skyscrapers (i.e., it is an accident): 0.008%</li>
</ul>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a><span class="fu">pAgivenB</span>(</span>
<span id="cb28-2"><a href="#cb28-2"></a>  <span class="at">pBgivenA =</span> <span class="dv">1</span>,</span>
<span id="cb28-3"><a href="#cb28-3"></a>  <span class="at">pA =</span> .<span class="dv">00005</span>,</span>
<span id="cb28-4"><a href="#cb28-4"></a>  <span class="at">pBgivenNotA =</span> .<span class="dv">00008</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3846272</code></pre>
</div>
</div>
</section><section id="sec-nateSilverExample3B" class="level4" data-number="16.5.3.2"><h4 data-number="16.5.3.2" class="anchored" data-anchor-id="sec-nateSilverExample3B">
<span class="header-section-number">16.5.3.2</span> Example 3B: The Second Plane Hit the World Trade Center</h4>
<p>Example 3B: Now, consider that a second plane just hit the World Trade Center. What is the probability that a terror attack occurred given that a second plane hit the World Trade Center?</p>
<ul>
<li>the revised <a href="#sec-baseRate">prior probability</a> that terrorists crash a plane into a Manhattan skyscraper (from <a href="#sec-nateSilverExample3A">Example 3A</a>): 38.46272%</li>
<li>the <a href="#sec-conditionalProbability">conditional probability</a> that a plane crashes into a Manhattan skyscraper if terrorists are attacking Manhattan skyscrapers: 100%</li>
<li>the <a href="#sec-conditionalProbability">conditional probability</a> that a plane crashes into a Manhattan skyscraper if terrorists are <em>not</em> attacking Manhattan skyscrapers (i.e., it is an accident): 0.008%</li>
</ul>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a><span class="fu">pAgivenB</span>(</span>
<span id="cb30-2"><a href="#cb30-2"></a>  <span class="at">pBgivenA =</span> <span class="dv">1</span>,</span>
<span id="cb30-3"><a href="#cb30-3"></a>  <span class="at">pA =</span> .<span class="dv">3846272</span>,</span>
<span id="cb30-4"><a href="#cb30-4"></a>  <span class="at">pBgivenNotA =</span> .<span class="dv">00008</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 0.999872</code></pre>
</div>
</div>
</section></section></section><section id="sec-baseRateFantasyFootball" class="level2" data-number="16.6"><h2 data-number="16.6" class="anchored" data-anchor-id="sec-baseRateFantasyFootball">
<span class="header-section-number">16.6</span> Base Rates Applied to Fantasy Football</h2>
<p>Base rates are also relevant to fantasy football. Unlike yardage (e.g., passing yards, rushing yards, receiving yards), touchdowns occur <em>relatively</em> less frequently. Whereas a solid Wide Receiver may log 100+ receptions and 1,200+ yards in a season, they may have “only” 8–14 receiving touchdowns in a given season. As noted in <a href="evaluating-prediction-accuracy.html#sec-differentErrorsDifferentCosts" class="quarto-xref"><span>Section 17.6.5</span></a>, lower base-rate events—including touchdowns—are harder to predict accurately. As noted by <a href="https://www.espn.com/fantasy/football/ffl/story?page=nfldk2k12_vbdwork">Harris (2012)</a>: “NFL statistical projections are basically impossible to get right. (Take it from someone who helps create them for a living.) Yes, we can do a passable job with yardage totals for players who don’t suffer unexpected injuries or depth-chart pratfalls. But so much of fantasy football hinges on touchdowns, and touchdowns are impossibly difficult to predict from season to season (let alone week to week).” (archived at <a href="https://perma.cc/4QNH-J2LD" class="uri">https://perma.cc/4QNH-J2LD</a>). Thus, it is important not to lend too much credence to predictions of touchdowns. Focus on other things that may be more predictable (and that may be indirectly prognostic of touchdowns) such as yards, carries/targets, receptions, depth of targets, red zone carries/targets, short distance carries/targets, etc.</p>
<p>[PROVIDE ACCURACY OF PROJECTIONS OF TOUCHDOWNS VS YARDAGE]</p>
<p>When dealing with numeric predictions (rather than categorical outcomes), the equivalent of the base rate is the average value. For instance, the “base rate” of fantasy points for a given position is the average number of fantasy points for that position. We could subdivide even further to identify, for instance, the “base rate” of fantasy points for the Wide Receiver at the top of the depth chart on a team.</p>
</section><section id="sec-baseRateRookiePerformance" class="level2" data-number="16.7"><h2 data-number="16.7" class="anchored" data-anchor-id="sec-baseRateRookiePerformance">
<span class="header-section-number">16.7</span> Base Rate of Rookie Performance</h2>
<section id="sec-baseRateRookiePerformanceQBs" class="level3" data-number="16.7.1"><h3 data-number="16.7.1" class="anchored" data-anchor-id="sec-baseRateRookiePerformanceQBs">
<span class="header-section-number">16.7.1</span> Quarterbacks</h3>
</section><section id="sec-baseRateRookiePerformanceRBs" class="level3" data-number="16.7.2"><h3 data-number="16.7.2" class="anchored" data-anchor-id="sec-baseRateRookiePerformanceRBs">
<span class="header-section-number">16.7.2</span> Running Backs</h3>
</section></section><section id="sec-accountForBaseRates" class="level2" data-number="16.8"><h2 data-number="16.8" class="anchored" data-anchor-id="sec-accountForBaseRates">
<span class="header-section-number">16.8</span> How to Account for Base Rates</h2>
<p>There are various ways to account for <a href="#sec-baseRate">base rates</a>, including the use of <a href="#sec-accountForBaseRatesActuarial">actuarial formulas</a> and the use of <a href="#sec-bayesianUpdating">Bayesian updating</a>.</p>
<section id="sec-accountForBaseRatesActuarial" class="level3" data-number="16.8.1"><h3 data-number="16.8.1" class="anchored" data-anchor-id="sec-accountForBaseRatesActuarial">
<span class="header-section-number">16.8.1</span> Actuarial Formula</h3>
<p>One approach to account for <a href="#sec-baseRate">base rates</a> is to use <a href="actuarial.html#sec-actuarialPrediction">actuarial formulas</a> (rather than <a href="actuarial.html#sec-humanJudgment">human judgment</a>) to make the predictions. <a href="actuarial.html#sec-actuarialPrediction">Actuarial formulas</a> based on <a href="multiple-regression.html">multiple regression</a> or <a href="#sec-machineLearning">machine learning</a> can account for the <a href="#sec-baseRate">base rate</a> of the event.</p>
</section><section id="sec-bayesianUpdating" class="level3" data-number="16.8.2"><h3 data-number="16.8.2" class="anchored" data-anchor-id="sec-bayesianUpdating">
<span class="header-section-number">16.8.2</span> Bayesian Updating</h3>
<p>Another approach to account for <a href="#sec-baseRate">base rates</a> is to leverage Bayes’ theorem, using Bayesian updating and the <a href="#sec-probabilityNomogram">probability nomogram</a>. Bayesian updating is a form of <a href="cognitive-bias.html#sec-heuristicsAnchoringAdjustment">anchoring and adjustment</a>; however, unlike the <a href="cognitive-bias.html#sec-heuristicsAnchoringAdjustment">anchoring and adjustment heuristic</a>, it is a systematic approach to <a href="cognitive-bias.html#sec-heuristicsAnchoringAdjustment">anchoring and adjustment</a> that anchors one’s predictions to the base rate, and then adjusts according to new information. That is, we start with a <a href="#sec-baseRate">pretest probability</a> (i.e., <a href="#sec-baseRate">base rate</a>) and update our predictions based on the extent of new information (i.e., the <a href="#sec-diagnosticLikelihoodRatio">likelihood ratio</a>).</p>
<p>To perform Bayesian updating involves comparing the relative probability of two outcomes, <span class="math inline">\(P(C | R)\)</span> versus <span class="math inline">\(P(\text{not } C | R)\)</span>. If we want to compare the relative probability of two outcomes, we can use the odds form of Bayes’ theorem, as in <a href="#eq-bayes5" class="quarto-xref">Equation&nbsp;<span>16.21</span></a>:</p>
<p><span id="eq-bayes5"><span class="math display">\[
\begin{aligned}
  P(C | R) &amp;= \frac{P(R | C) \cdot P(C_i)}{P(R_i)} \\
  P(\text{not } C | R) &amp;= \frac{P(R | \text{not } C) \cdot P(\text{not } C_i)}{P(R_i)} \\
  \frac{P(C | R)}{P(\text{not } C | R)} &amp;= \frac{\frac{P(R | C) \cdot P(C_i)}{P(R_i)}}{\frac{P(R | \text{not } C) \cdot P(\text{not } C_i)}{P(R_i)}} \\
  &amp;= \frac{P(R | C) \cdot P(C_i)}{P(R | \text{not } C) \cdot P(\text{not } C_i)} \\
  &amp;= \frac{P(C_i)}{P(\text{not } C_i)} \times \frac{P(R | C)}{P(R | \text{not } C)} \\
  \text{posterior odds} &amp;= \text{prior odds} \times \text{likelihood ratio}
\end{aligned}
\tag{16.21}\]</span></span></p>
<p>As presented in <a href="#eq-bayes5" class="quarto-xref">Equation&nbsp;<span>16.21</span></a>, the posttest (or posterior) odds are equal to the pretest odds multiplied by the <a href="#sec-diagnosticLikelihoodRatio">likelihood ratio</a>. Below, we describe the <a href="#sec-diagnosticLikelihoodRatio">likelihood ratio</a>.</p>
<section id="sec-diagnosticLikelihoodRatio" class="level4" data-number="16.8.2.1"><h4 data-number="16.8.2.1" class="anchored" data-anchor-id="sec-diagnosticLikelihoodRatio">
<span class="header-section-number">16.8.2.1</span> Diagnostic Likelihood Ratio</h4>
<p>A likelihood ratio is the ratio of two probabilities. It can be used to compare the likelihood of two possibilities. The diagnostic likelihood ratio is an index of the predictive validity of an instrument: it is the ratio of the probability that a test result is correct to the probability that the test result is incorrect. The diagnostic likelihood ratio is also called the risk ratio. There are two types of diagnostic likelihood ratios: the <a href="#sec-positiveLikelihoodRatio">positive likelihood ratio</a> and the <a href="#sec-negativeLikelihoodRatio">negative likelihood ratio</a>.</p>
<section id="sec-positiveLikelihoodRatio" class="level5" data-number="16.8.2.1.1"><h5 data-number="16.8.2.1.1" class="anchored" data-anchor-id="sec-positiveLikelihoodRatio">
<span class="header-section-number">16.8.2.1.1</span> Positive Likelihood Ratio (LR+)</h5>
<p>The positive likelihood ratio (LR+) compares the <a href="evaluating-prediction-accuracy.html#sec-sensitivity">true positive rate</a> to the <a href="evaluating-prediction-accuracy.html#sec-falsePositiveRate">false positive rate</a>. Positive likelihood ratio values range from 1 to infinity. Higher values reflect greater accuracy, because it indicates the degree to which a <a href="evaluating-prediction-accuracy.html#sec-truePositive">true positive</a> is more likely than a <a href="evaluating-prediction-accuracy.html#sec-falsePositive">false positive</a>. The formula for calculating the positive likelihood ratio is in <a href="#eq-positiveLikelihoodRatio" class="quarto-xref">Equation&nbsp;<span>16.22</span></a>.</p>
<p><span id="eq-positiveLikelihoodRatio"><span class="math display">\[
\begin{aligned}
  \text{positive likelihood ratio (LR+)} &amp;= \frac{\text{TPR}}{\text{FPR}} \\
  &amp;= \frac{P(R|C)}{P(R|\text{not } C)} \\
  &amp;= \frac{P(R|C)}{1 - P(\text{not } R|\text{not } C)} \\
  &amp;= \frac{\text{sensitivity}}{1 - \text{specificity}}
\end{aligned}
\tag{16.22}\]</span></span></p>
</section><section id="sec-negativeLikelihoodRatio" class="level5" data-number="16.8.2.1.2"><h5 data-number="16.8.2.1.2" class="anchored" data-anchor-id="sec-negativeLikelihoodRatio">
<span class="header-section-number">16.8.2.1.2</span> Negative Likelihood Ratio (LR−)</h5>
<p>The negative likelihood ratio (LR−) compares the <a href="evaluating-prediction-accuracy.html#sec-falseNegativeRate">false negative rate</a> to the <a href="evaluating-prediction-accuracy.html#sec-specificity">true negative rate</a>. Negative likelihood ratio values range from 0 to 1. Smaller values reflect greater accuracy, because it indicates that a <a href="evaluating-prediction-accuracy.html#sec-falseNegative">false negative</a> is less likely than a <a href="evaluating-prediction-accuracy.html#sec-trueNegative">true negative</a>. The formula for calculating the negative likelihood ratio is in <a href="#eq-negativeLikelihoodRatio" class="quarto-xref">Equation&nbsp;<span>16.23</span></a>.</p>
<p><span id="eq-negativeLikelihoodRatio"><span class="math display">\[
\begin{aligned}
  \text{negative likelihood ratio } (\text{LR}-) &amp;= \frac{\text{FNR}}{\text{TNR}} \\
  &amp;= \frac{P(\text{not } R|C)}{P(\text{not } R|\text{not } C)} \\
  &amp;= \frac{1 - P(R|C)}{P(\text{not } R|\text{not } C)} \\
  &amp;= \frac{1 - \text{sensitivity}}{\text{specificity}}
\end{aligned}
\tag{16.23}\]</span></span></p>
</section></section><section id="sec-probabilityNomogram" class="level4" data-number="16.8.2.2"><h4 data-number="16.8.2.2" class="anchored" data-anchor-id="sec-probabilityNomogram">
<span class="header-section-number">16.8.2.2</span> Probability Nomogram</h4>
<p>Using <a href="#sec-bayesTheorem">Bayes’ theorem</a> (described in <a href="#sec-bayesTheorem" class="quarto-xref"><span>Section 16.3.3</span></a>), solving for posttest odds (based on pretest odds and the <a href="#sec-diagnosticLikelihoodRatio">likelihood ratio</a>, as in <a href="#eq-bayes5" class="quarto-xref">Equation&nbsp;<span>16.21</span></a>), and converting odds to probabilities, we can use a Fagan probability nomogram to determine the posttest probability following a test result. The calculation of posttest probability is described in INSERT. A <em>probability nomogram</em> (aka Fagan nomogram) is a way of visually applying <a href="#sec-bayesTheorem">Bayes’ theorem</a> to determine the posttest probability of having a condition based on the <a href="#sec-baseRate">pretest (or prior) probability</a> and <a href="#sec-diagnosticLikelihoodRatio">likelihood ratio</a>, as depicted in <a href="#fig-probabilityNomogram" class="quarto-xref">Figure&nbsp;<span>16.1</span></a>. To use a probability nomogram, connect the dots from the starting probability (left line) with the <a href="#sec-diagnosticLikelihoodRatio">likelihood ratio</a> (middle line) to see the updated probability. The updated (posttest) probability is where the connecting line crosses the third, right line.</p>
<div id="fig-probabilityNomogram" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Probability Nomogram. (Figure retrieved from https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Fagan_nomogram.svg/945px-Fagan_nomogram.svg.png)">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-probabilityNomogram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/probabilityNomogram.png" class="img-fluid figure-img" style="width:50.0%" alt="Probability Nomogram. (Figure retrieved from https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Fagan_nomogram.svg/945px-Fagan_nomogram.svg.png)">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-probabilityNomogram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16.1: Probability Nomogram. (Figure retrieved from <a href="https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Fagan_nomogram.svg/945px-Fagan_nomogram.svg.png">https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Fagan_nomogram.svg/945px-Fagan_nomogram.svg.png</a>).
</figcaption></figure>
</div>
<p>For instance, if the starting probability is 0.5% and the <a href="#sec-diagnosticLikelihoodRatio">likelihood ratio</a> is 10 (e.g., <a href="evaluating-prediction-accuracy.html#sec-sensitivity">sensitivity</a> = .90, <a href="evaluating-prediction-accuracy.html#sec-specificity">specificity</a> = .91: <span class="math inline">\(\text{likelihood ratio} = \frac{\text{sensitivity}}{1 - \text{specificity}} = \frac{.9}{1-.91} = 10\)</span>) from a positive test (i.e., <a href="#sec-positiveLikelihoodRatio">positive likelihood ratio</a>), the updated probability is less than 5%, as depicted in <a href="#fig-probabilityNomogramLine" class="quarto-xref">Figure&nbsp;<span>16.2</span></a>.</p>
<p>An interactive probability nomogram is available at the following link: <a href="https://jamaevidence.mhmedical.com/data/calculators/LR_nomogram.html" class="uri">https://jamaevidence.mhmedical.com/data/calculators/LR_nomogram.html</a> (archived at <a href="https://perma.cc/Z3SW-QMJ3" class="uri">https://perma.cc/Z3SW-QMJ3</a>).</p>
<p>The <a href="https://github.com/DevPsyLab/petersenlab"><code>petersenlab</code></a> package <span class="citation" data-cites="R-petersenlab">(<a href="references.html#ref-R-petersenlab" role="doc-biblioref">Petersen, 2024a</a>)</span> contains the <code>posttestProbability()</code> function that estimates the posttest probability of an event, given the <a href="#sec-baseRate">pretest probability</a> and the <a href="#sec-diagnosticLikelihoodRatio">likelihood ratio</a>, or given the <a href="#sec-baseRate">pretest probability</a> and the <a href="evaluating-prediction-accuracy.html#sec-sensitivity">sensitivity</a> (SN) and <a href="evaluating-prediction-accuracy.html#sec-specificity">specificity</a> (SP) of the test.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a>petersenlab<span class="sc">::</span><span class="fu">posttestProbability</span>(</span>
<span id="cb32-2"><a href="#cb32-2"></a>  <span class="at">pretestProb =</span> .<span class="dv">005</span>,</span>
<span id="cb32-3"><a href="#cb32-3"></a>  <span class="at">likelihoodRatio =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 0.04784689</code></pre>
</div>
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1"></a>petersenlab<span class="sc">::</span><span class="fu">posttestProbability</span>(</span>
<span id="cb34-2"><a href="#cb34-2"></a>  <span class="at">pretestProb =</span> .<span class="dv">005</span>,</span>
<span id="cb34-3"><a href="#cb34-3"></a>  <span class="at">SN =</span> .<span class="dv">90</span>,</span>
<span id="cb34-4"><a href="#cb34-4"></a>  <span class="at">SP =</span> .<span class="dv">91</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 0.04784689</code></pre>
</div>
</div>
<p>The function can also estimate the posttest probability of an event given the number of <a href="evaluating-prediction-accuracy.html#sec-truePositive">true positives</a> (TP), <a href="evaluating-prediction-accuracy.html#sec-trueNegative">true negatives</a> (TN), <a href="evaluating-prediction-accuracy.html#sec-falsePositive">false positives</a> (FP), and <a href="evaluating-prediction-accuracy.html#sec-falseNegative">false negatives</a> (FN):</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1"></a>petersenlab<span class="sc">::</span><span class="fu">posttestProbability</span>(</span>
<span id="cb36-2"><a href="#cb36-2"></a>  <span class="at">TP =</span> <span class="dv">450</span>,</span>
<span id="cb36-3"><a href="#cb36-3"></a>  <span class="at">TN =</span> <span class="dv">90545</span>,</span>
<span id="cb36-4"><a href="#cb36-4"></a>  <span class="at">FP =</span> <span class="dv">8955</span>,</span>
<span id="cb36-5"><a href="#cb36-5"></a>  <span class="at">FN =</span> <span class="dv">50</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 0.04784689</code></pre>
</div>
</div>
<p>We discuss <a href="evaluating-prediction-accuracy.html#sec-truePositive">true positives</a> (TP), <a href="evaluating-prediction-accuracy.html#sec-trueNegative">true negatives</a> (TN), <a href="evaluating-prediction-accuracy.html#sec-falsePositive">false positives</a> (FP), <a href="evaluating-prediction-accuracy.html#sec-falseNegative">false negatives</a> (FN), <a href="evaluating-prediction-accuracy.html#sec-sensitivity">sensitivity</a> (SN), and <a href="evaluating-prediction-accuracy.html#sec-specificity">specificity</a> (SP) in <a href="evaluating-prediction-accuracy.html#sec-thresholdDependentAccuracy" class="quarto-xref"><span>Section 17.6</span></a> (<a href="evaluating-prediction-accuracy.html#sec-decisionOutcomes" class="quarto-xref"><span>Section 17.6.1</span></a> and <a href="evaluating-prediction-accuracy.html#sec-sensitivitySpecificityPPVnpv" class="quarto-xref"><span>Section 17.6.6</span></a>).</p>
<p>If the starting probability is 0.5% and the <a href="#sec-diagnosticLikelihoodRatio">likelihood ratio</a> is 0.11 from a negative test (i.e., <a href="#sec-negativeLikelihoodRatio">negative likelihood ratio</a>), the updated probability is nearly indistinguishable from zero (0.05%).</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1"></a>petersenlab<span class="sc">::</span><span class="fu">posttestProbability</span>(</span>
<span id="cb38-2"><a href="#cb38-2"></a>  <span class="at">pretestProb =</span> .<span class="dv">005</span>,</span>
<span id="cb38-3"><a href="#cb38-3"></a>  <span class="at">likelihoodRatio =</span> <span class="fl">0.11</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0005524584</code></pre>
</div>
</div>
<div id="fig-probabilityNomogramLine" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Probability Nomogram. (Figure retrieved from https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Fagan_nomogram.svg/945px-Fagan_nomogram.svg.png). Also provided in: @Petersen2024a and @PetersenPrinciplesPsychAssessment.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-probabilityNomogramLine-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/probabilityNomogramLine.png" class="img-fluid figure-img" style="width:50.0%" alt="Probability Nomogram. (Figure retrieved from https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Fagan_nomogram.svg/945px-Fagan_nomogram.svg.png). Also provided in: @Petersen2024a and @PetersenPrinciplesPsychAssessment.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-probabilityNomogramLine-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16.2: Probability Nomogram Example. (Figure adapted from <a href="https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Fagan_nomogram.svg/945px-Fagan_nomogram.svg.png">https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Fagan_nomogram.svg/945px-Fagan_nomogram.svg.png</a>. Also provided in: <span class="citation" data-cites="Petersen2024a">Petersen (<a href="references.html#ref-Petersen2024a" role="doc-biblioref">2024b</a>)</span> and <span class="citation" data-cites="PetersenPrinciplesPsychAssessment">Petersen (<a href="references.html#ref-PetersenPrinciplesPsychAssessment" role="doc-biblioref">2024c</a>)</span>.)
</figcaption></figure>
</div>
<p>A probability nomogram calculator can be found at the following link: <a href="http://araw.mede.uic.edu/cgi-bin/testcalc.pl">http://araw.mede.uic.edu/cgi-bin/testcalc.pl</a> (archived at <a href="https://perma.cc/X8TF-7YBX" class="uri">https://perma.cc/X8TF-7YBX</a>). The <a href="https://github.com/DevPsyLab/petersenlab"><code>petersenlab</code></a> package <span class="citation" data-cites="R-petersenlab">(<a href="references.html#ref-R-petersenlab" role="doc-biblioref">Petersen, 2024a</a>)</span> contains the <code>nomogrammer()</code> function that creates a nomogram plot using the <a href="#sec-positiveLikelihoodRatio">positive</a> and <a href="#sec-negativeLikelihoodRatio">negative</a> <a href="#sec-diagnosticLikelihoodRatio">likelihood ratio</a> or using the <a href="evaluating-prediction-accuracy.html#sec-sensitivity">sensitivity</a> (SN) and <a href="evaluating-prediction-accuracy.html#sec-specificity">specificity</a> (SP) of the test, as adapted from Adam Chekroud (<a href="https://github.com/achekroud/nomogrammer" class="uri">https://github.com/achekroud/nomogrammer</a>):</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1"></a>petersenlab<span class="sc">::</span><span class="fu">nomogrammer</span>(</span>
<span id="cb40-2"><a href="#cb40-2"></a>  <span class="at">pretestProb =</span> .<span class="dv">005</span>,</span>
<span id="cb40-3"><a href="#cb40-3"></a>  <span class="at">SN =</span> <span class="fl">0.90</span>,</span>
<span id="cb40-4"><a href="#cb40-4"></a>  <span class="at">SP =</span> <span class="fl">0.91</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="base-rates_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The blue line indicates the <a href="#posttestProbability">posterior probability</a> of the condition given a positive test. The pink line indicates the <a href="#posttestProbability">posterior probability</a> of the condition given a negative test.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a>petersenlab<span class="sc">::</span><span class="fu">nomogrammer</span>(</span>
<span id="cb41-2"><a href="#cb41-2"></a>  <span class="at">pretestProb =</span> .<span class="dv">005</span>,</span>
<span id="cb41-3"><a href="#cb41-3"></a>  <span class="at">PLR =</span> <span class="dv">10</span>,</span>
<span id="cb41-4"><a href="#cb41-4"></a>  <span class="at">NLR =</span> <span class="fl">0.11</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="base-rates_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The function can also create a nomogram plot using the <a href="evaluating-prediction-accuracy.html#sec-truePositive">true positives</a> (TP), <a href="evaluating-prediction-accuracy.html#sec-trueNegative">true negatives</a> (TN), <a href="evaluating-prediction-accuracy.html#sec-falsePositive">false positives</a> (FP), and <a href="evaluating-prediction-accuracy.html#sec-falseNegative">false negatives</a> (FN):</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1"></a>petersenlab<span class="sc">::</span><span class="fu">nomogrammer</span>(</span>
<span id="cb42-2"><a href="#cb42-2"></a>  <span class="at">TP =</span> <span class="dv">450</span>,</span>
<span id="cb42-3"><a href="#cb42-3"></a>  <span class="at">TN =</span> <span class="dv">90545</span>,</span>
<span id="cb42-4"><a href="#cb42-4"></a>  <span class="at">FP =</span> <span class="dv">8955</span>,</span>
<span id="cb42-5"><a href="#cb42-5"></a>  <span class="at">FN =</span> <span class="dv">50</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="base-rates_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The function can also create a nomogram plot using the <a href="evaluating-prediction-accuracy.html#sec-sensitivity">sensitivity</a> (SN) and <a href="evaluating-prediction-accuracy.html#sec-selectionRatio">selection rate</a> of the test. Here is a nomogram plot from the <a href="#sec-baseRatesOverview">HIV example</a>:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1"></a>petersenlab<span class="sc">::</span><span class="fu">nomogrammer</span>(</span>
<span id="cb43-2"><a href="#cb43-2"></a>  <span class="at">pretestProb =</span> .<span class="dv">003</span>,</span>
<span id="cb43-3"><a href="#cb43-3"></a>  <span class="at">SN =</span> .<span class="dv">95</span>,</span>
<span id="cb43-4"><a href="#cb43-4"></a>  <span class="at">selectionRate =</span> .<span class="dv">01</span></span>
<span id="cb43-5"><a href="#cb43-5"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="base-rates_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Here is a nomogram plot from the <a href="#sec-cabExample">cab example</a> <span class="citation" data-cites="Kahneman2011">(<a href="references.html#ref-Kahneman2011" role="doc-biblioref">Kahneman, 2011</a>)</span>:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1"></a>petersenlab<span class="sc">::</span><span class="fu">nomogrammer</span>(</span>
<span id="cb44-2"><a href="#cb44-2"></a>  <span class="at">pretestProb =</span> .<span class="dv">15</span>,</span>
<span id="cb44-3"><a href="#cb44-3"></a>  <span class="at">SN =</span> .<span class="dv">80</span>,</span>
<span id="cb44-4"><a href="#cb44-4"></a>  <span class="at">SP =</span> .<span class="dv">80</span></span>
<span id="cb44-5"><a href="#cb44-5"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="base-rates_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The function can also create a nomogram plot using the <a href="evaluating-prediction-accuracy.html#sec-sensitivity">sensitivity</a> (SN) and <a href="evaluating-prediction-accuracy.html#sec-falsePositiveRate">false positive rate</a> of the test. Here is a nomogram plot from <a href="#sec-nateSilverExample1">Example 1</a> from <span class="citation" data-cites="Silver2012">Silver (<a href="references.html#ref-Silver2012" role="doc-biblioref">2012</a>)</span>:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1"></a>petersenlab<span class="sc">::</span><span class="fu">nomogrammer</span>(</span>
<span id="cb45-2"><a href="#cb45-2"></a>  <span class="at">pretestProb =</span> .<span class="dv">04</span>,</span>
<span id="cb45-3"><a href="#cb45-3"></a>  <span class="at">SN =</span> .<span class="dv">50</span>,</span>
<span id="cb45-4"><a href="#cb45-4"></a>  <span class="at">FPR =</span> .<span class="dv">05</span></span>
<span id="cb45-5"><a href="#cb45-5"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="base-rates_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Here is a nomogram plot from <a href="#sec-nateSilverExample2">Example 2</a> from <span class="citation" data-cites="Silver2012">Silver (<a href="references.html#ref-Silver2012" role="doc-biblioref">2012</a>)</span>:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a>petersenlab<span class="sc">::</span><span class="fu">nomogrammer</span>(</span>
<span id="cb46-2"><a href="#cb46-2"></a>  <span class="at">pretestProb =</span> .<span class="dv">014</span>,</span>
<span id="cb46-3"><a href="#cb46-3"></a>  <span class="at">SN =</span> .<span class="dv">75</span>,</span>
<span id="cb46-4"><a href="#cb46-4"></a>  <span class="at">FPR =</span> .<span class="dv">10</span></span>
<span id="cb46-5"><a href="#cb46-5"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="base-rates_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Here is a nomogram plot from <a href="#sec-nateSilverExample3A">Example 3A</a> from <span class="citation" data-cites="Silver2012">Silver (<a href="references.html#ref-Silver2012" role="doc-biblioref">2012</a>)</span>:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1"></a>petersenlab<span class="sc">::</span><span class="fu">nomogrammer</span>(</span>
<span id="cb47-2"><a href="#cb47-2"></a>  <span class="at">pretestProb =</span> .<span class="dv">00005</span>,</span>
<span id="cb47-3"><a href="#cb47-3"></a>  <span class="at">SN =</span> <span class="dv">1</span>,</span>
<span id="cb47-4"><a href="#cb47-4"></a>  <span class="at">FPR =</span> .<span class="dv">00008</span></span>
<span id="cb47-5"><a href="#cb47-5"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="base-rates_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Here is a nomogram plot from <a href="#sec-nateSilverExample3B">Example 3B</a> from <span class="citation" data-cites="Silver2012">Silver (<a href="references.html#ref-Silver2012" role="doc-biblioref">2012</a>)</span>:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1"></a>petersenlab<span class="sc">::</span><span class="fu">nomogrammer</span>(</span>
<span id="cb48-2"><a href="#cb48-2"></a>  <span class="at">pretestProb =</span> .<span class="dv">3846272</span>,</span>
<span id="cb48-3"><a href="#cb48-3"></a>  <span class="at">SN =</span> <span class="dv">1</span>,</span>
<span id="cb48-4"><a href="#cb48-4"></a>  <span class="at">FPR =</span> .<span class="dv">00008</span></span>
<span id="cb48-5"><a href="#cb48-5"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="base-rates_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section><section id="sec-informalUpdating" class="level4" data-number="16.8.2.3"><h4 data-number="16.8.2.3" class="anchored" data-anchor-id="sec-informalUpdating">
<span class="header-section-number">16.8.2.3</span> Informal Updating</h4>
<p><span class="citation" data-cites="Kahneman2011">Kahneman (<a href="references.html#ref-Kahneman2011" role="doc-biblioref">2011</a>)</span> provides the following guidance for an informal approach to updating that anchors predictions to the base rate:</p>
<ol type="1">
<li>Start with the “baseline prediction” (i.e., base rate or average outcome).</li>
<li>Generate or identify your “intuitive prediction”—the number that matches your impression of the evidence.</li>
<li>Your posterior prediction should fall somewhere between the baseline prediction and the intuitive prediction. “In the default case of no useful evidence, you stay with the baseline [prediction]. At the other extreme, you also stay with your initial [i.e., intuitive] prediction. This will happen, of course, only if you remain completely confident in your initial prediction after a critical review of the evidence that supports it. In most cases you will find some reasons to doubt that the correlation between your intuitive judgment and the truth is perfect, and you will end up somewhere between the two poles.” (pp.&nbsp;191–192). Base the extent of adjustment (from the baseline prediction) on the magnitude of the correlation between your prediction/evidence and the truth, which acts similar to the <a href="#sec-diagnosticLikelihoodRatio">likelihood ratio</a>. For instance, if the correlation between your prediction/evidence and the truth is .5, move 50% of the difference from the baseline prediction to the intuitive prediction.</li>
</ol></section></section></section><section id="sec-baseRatesConclusion" class="level2" data-number="16.9"><h2 data-number="16.9" class="anchored" data-anchor-id="sec-baseRatesConclusion">
<span class="header-section-number">16.9</span> Conclusion</h2>
<p>Fantasy performance—and behavior more generally—is challenging to predict. People commonly demonstrate <a href="cognitive-bias.html#sec-cognitiveBiases">biases</a> and <a href="cognitive-bias.html#sec-fallacies">fallacies</a> when making predictions. People tend to ignore base rates (<a href="cognitive-bias.html#sec-fallaciesBaseRate">base rate fallacy</a>) when making predictions. They also tend to confuse inverse conditional probabilities (<a href="#sec-inverseFallacy">conditional probability fallacy</a>). <a href="#sec-bayesTheorem">Bayes’ theorem</a> provides a way to convert from one conditional probability to its inverse conditional probability using the <a href="#sec-baseRate">base rate</a> of each event. There are various ways to account for <a href="#sec-baseRate">base rates</a> for more accurate predictions, including through the use of <a href="#sec-accountForBaseRatesActuarial">actuarial formulas</a>, <a href="#sec-bayesianUpdating">Bayesian updating</a>, and more <a href="#sec-informalUpdating">informal approaches</a>. <a href="#sec-bayesianUpdating">Bayesian updating</a> uses <a href="#sec-bayesTheorem">Bayes’ theorem</a> to calculate a posttest probability from a <a href="#sec-baseRate">pretest probability</a> and a test result (<a href="#sec-diagnosticLikelihoodRatio">likelihood ratio</a>). The <a href="#sec-probabilityNomogram">probability nomogram</a> is a visual approach to <a href="#sec-bayesianUpdating">Bayesian updating</a>.</p>
</section><section id="sec-baseRatesSessionInfo" class="level2" data-number="16.10"><h2 data-number="16.10" class="anchored" data-anchor-id="sec-baseRatesSessionInfo">
<span class="header-section-number">16.10</span> Session Info</h2>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1"></a><span class="fu">sessionInfo</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>R version 4.4.1 (2024-06-14)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 22.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

time zone: UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] petersenlab_1.0.10

loaded via a namespace (and not attached):
 [1] gtable_0.3.5       xfun_0.48          ggplot2_3.5.1      htmlwidgets_1.6.4 
 [5] psych_2.4.6.26     lattice_0.22-6     quadprog_1.5-8     vctrs_0.6.5       
 [9] tools_4.4.1        generics_0.1.3     stats4_4.4.1       parallel_4.4.1    
[13] tibble_3.2.1       fansi_1.0.6        cluster_2.1.6      pkgconfig_2.0.3   
[17] data.table_1.16.2  checkmate_2.3.2    RColorBrewer_1.1-3 lifecycle_1.0.4   
[21] compiler_4.4.1     farver_2.1.2       stringr_1.5.1      munsell_0.5.1     
[25] mnormt_2.1.1       mitools_2.4        htmltools_0.5.8.1  htmlTable_2.4.3   
[29] Formula_1.2-5      pillar_1.9.0       Hmisc_5.1-3        rpart_4.1.23      
[33] nlme_3.1-164       lavaan_0.6-19      tidyselect_1.2.1   digest_0.6.37     
[37] mvtnorm_1.3-1      stringi_1.8.4      dplyr_1.1.4        reshape2_1.4.4    
[41] purrr_1.0.2        labeling_0.4.3     fastmap_1.2.0      grid_4.4.1        
[45] colorspace_2.1-1   cli_3.6.3          magrittr_2.0.3     base64enc_0.1-3   
[49] utf8_1.2.4         pbivnorm_0.6.0     foreign_0.8-86     withr_3.0.1       
[53] scales_1.3.0       backports_1.5.0    rmarkdown_2.28     nnet_7.3-19       
[57] gridExtra_2.3      evaluate_1.0.1     knitr_1.48         mix_1.0-12        
[61] viridisLite_0.4.2  rlang_1.1.4        Rcpp_1.0.13        xtable_1.8-4      
[65] glue_1.8.0         DBI_1.2.3          rstudioapi_0.17.1  jsonlite_1.8.9    
[69] R6_2.5.1           plyr_1.8.9        </code></pre>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-Corston2000" class="csl-entry" role="listitem">
Corston, R., &amp; Colman, A. M. (2000). <em>A crash course in SPSS for <span>Windows</span></em>. Wiley-Blackwell.
</div>
<div id="ref-Kahneman2011" class="csl-entry" role="listitem">
Kahneman, D. (2011). <em>Thinking, fast and slow</em>. <span>Farrar, Straus, and Giroux</span>.
</div>
<div id="ref-R-petersenlab" class="csl-entry" role="listitem">
Petersen, I. T. (2024a). <em><span class="nocase">petersenlab</span>: A collection of <span>R</span> functions by the <span>Petersen</span> <span>Lab</span></em>. <a href="https://github.com/DevPsyLab/petersenlab">https://github.com/DevPsyLab/petersenlab</a>
</div>
<div id="ref-PetersenPrinciplesPsychAssessment" class="csl-entry" role="listitem">
Petersen, I. T. (2024c). <em>Principles of psychological assessment: With applied examples in <span>R</span></em>. University of Iowa Libraries. <a href="https://doi.org/10.25820/work.007199">https://doi.org/10.25820/work.007199</a>
</div>
<div id="ref-Petersen2024a" class="csl-entry" role="listitem">
Petersen, I. T. (2024b). <em>Principles of psychological assessment: With applied examples in <span>R</span></em>. <span>Chapman and Hall/CRC</span>. <a href="https://doi.org/10.1201/9781003357421">https://doi.org/10.1201/9781003357421</a>
</div>
<div id="ref-Silver2012" class="csl-entry" role="listitem">
Silver, N. (2012). <em>The signal and the noise: Why so many predictions fail–but some don’t</em>. Penguin.
</div>
</div>
</section></main><!-- /main --><div id="disqus_thread"></div>
<script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
    /*
    var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://fantasyfootballanalytics.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script><noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a>
</noscript>
<h3>Feedback</h3>

<div class="feedback">
    Please consider providing feedback about this textbook, so that I can make it as helpful as possible. You can provide feedback at the following link:
    
    <a href="https://forms.gle/LsnVKwqmS1VuxWD18">https://forms.gle/LsnVKwqmS1VuxWD18</a>
</div>

<h3>Email Notification</h3>

<div class="rmdsale">
The online version of this book will remain open access. If you want to know when the print version of the book is for sale, enter your email below so I can let you know.
<br><iframe src="https://docs.google.com/forms/d/e/1FAIpQLSccMKaTBXzMBmcy4myCNQnL8mCgRczh0Eg_Pw3c15bork7-xQ/viewform?embedded=true" width="640" height="750" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>

</div>
<script id="dsq-count-scr" src="//fantasyfootballanalytics.disqus.com/count.js" async=""></script><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/isaactpetersen\.github\.io\/Fantasy-Football-Analytics-Textbook");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./actuarial.html" class="pagination-link" aria-label="Judgment Versus Actuarial Approaches to Prediction">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Judgment Versus Actuarial Approaches to Prediction</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./evaluating-prediction-accuracy.html" class="pagination-link" aria-label="Evaluation of Prediction/Forecasting Accuracy">
        <span class="nav-page-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Evaluation of Prediction/Forecasting Accuracy</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>“Fantasy Football Analytics: Statistics, Prediction, and Empiricism Using R” was written by <a href="https://psychology.uiowa.edu/people/isaac-petersen">Isaac T. Petersen</a>.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/isaactpetersen/Fantasy-Football-Analytics-Textbook/edit/main/base-rates.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/isaactpetersen/Fantasy-Football-Analytics-Textbook/blob/main/base-rates.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li><li><a href="https://github.com/isaactpetersen/Fantasy-Football-Analytics-Textbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>


</body></html>