# The Fantasy Draft {#sec-draft}

## Getting Started {#sec-draftGettingStarted}

### Load Packages {#sec-draftLoadPackages}

```{r}

```

## Types of Fantasy Drafts {#sec-draftTypes}

There are several types of drafts in fantasy football.
The most common types of drafts are snake drafts and auction drafts.

### Snake Draft {#sec-draftSnake}

In a snake draft, the participants (i.e., managers) are assigned a draft order.
In the first round, the managers draft in that order.
In the second round, the managers draft in reverse order.
It continues to "snake" in this way, round after round, so that the person who has the first pick in a given round has the last pick in the next round, and whoever has the last pick in a given round has the first pick in the next round.

### Auction Draft {#sec-draftAuction}

In an auction draft, the managers are assigned a nomination order and there is a salary cap (e.g., $200).
The first manager chooses which player to nominate.
Then, the managers bid on that player like in an auction.
In order to bid, the manager must raise the price by at least $1.
If two managers want to obtain the same player, they may continue to raise the amount until one manager backs out and is no longer to bid by raising the price.
The highest bidder wins (i.e., drafts) that player.
Then, the second manager nominates a player, and the managers bid on that player.
This process repeats until all teams have drafted their allotment of players.

In the auction draft, unlike the snake draft, all players are available to all teams.
For instance, in the snake draft, the first 9 players drafted are unavailable to the 10th pick of the first round.
So, if you have the 10th pick and want the top-ranked player, this player would not be available to you in the snake draft.
However, in the auction draft, every player is available to every manager, so long as the manager is able and willing to bid enough.

## Draft Strategy {#sec-draftStrategy}

### Overview {#sec-draftStrategyOverview}

There is no one "right" draft strategy.
Sometimes it works best to "zig" when everyone else is "zagging".
For instance, if you notice that everyone else is drafting Wide Receivers, this may mean that other managers are over-valuing Wide Receivers, and this could be a nice opportunity to draft a Running Back for good value.

In general, you will first want to generate the rankings you will use to select which players to prioritize.
You may generate your rankings based one or more of the following:

- your [evaluation of players](player-evaluation.qmd)
- [expert or aggregated rankings](#sec-fantasyValueRankings)
- [layperson rankings](#sec-fantasyValueADPAAV)
    - players' [Average Draft Position](#sec-fantasyValueADPAAV) (ADP) in other league drafts (for [snake drafts](#sec-draftStrategySnake))
    - players' [Average Auction Value](#sec-fantasyValueADPAAV) (AAV) in other league drafts (for [auction drafts](sec-draftStrategyAuction))
- [expert or aggregated projections](#sec-fantasyValueProjections)
- [indices derived from rankings and projections](#sec-fantasyValueIndices)

Section @sec-fantasyValueSources describes where to obtain [aggregated rankings](#sec-fantasyValueRankings), [aggregated projections](#sec-fantasyValueProjections), [ADP](#sec-fantasyValueADPAAV), and [AAV](#sec-fantasyValueADPAAV) data.

An important concept in the draft is "[dropoff](#sec-fantasyValueDropoff)", which is described in Section @sec-fantasyValueDropoff.
[*Dropoff*](#sec-fantasyValueDropoff) at a given position, is the difference—in terms of projected fantasy points—between (a) the best available player remaining at that position and (b) the second-best available player remaining at that position.
If there is a bigger [dropoff](#sec-fantasyValueDropoff) at a given position, there may be greater value in drafting the top player from that position.
For instance, consider the following scenario:
"Quarterback A" is projected to score 325 points, and "Quarterback B" is projected to score 320 points.
"Tight End A" is projected to score 230 points, and "Tight End B" is projected to score 150 points.
In this example, there is a much greater [dropoff](#sec-fantasyValueDropoff) for Tight Ends than there is for Quarterbacks.
Thus, even though "Quarterback A" is projected to score more points than "Tight End A", "Tight End A" may be more valuable because there is still a good Quarterback available if someone else drafts "Quarterback A".

Another important concept is a player's [value over a typical replacement player](#sec-fantasyValueVORP) at that position (shortened to "value over replacement player"; VORP), which is described in Section @sec-fantasyValueVORP.

Another important concept is a player's [uncertainty](#sec-fantasyValueUncertainty), which is described in Section @sec-fantasyValueUncertainty.

In both [snake](#sec-draftStrategySnake) and [auction](#sec-draftStrategyAuction) draft formats, your goal is to draft the team whose weekly starting lineup scores the most points and thus the collection of players with the greatest [VORP](#sec-fantasyValueVORP).
For your starting lineup, it may make sense—especially with your earliest selections—when comparing two players with equivalent [VORP](#sec-fantasyValueVORP), to prioritize players with higher [consistency](#sec-evalHistoricalConsistency) and lower [uncertainty](#sec-fantasyValueUncertainty), because they may be considered "safer" with a higher floor.
However, when drafting players for your bench, it make make more sense to prioritize high risk, high reward players with greater [uncertainty](#sec-fantasyValueUncertainty), because they may have a higher ceiling (i.e., this is a *lower* risk kind of selection with later picks).
The Spurs in the National Basketball Association (NBA) were well-reputed for [excelling in this draft strategy](https://harvardsportsanalysis.org/2013/11/beating-the-nba-draft-does-any-team-outperform-expectations/) (archived at <https://perma.cc/X7NW-WZC6>).
They frequently used their second-round picks to draft high-risk, high-reward players.
Sometimes, the secound round pick was a bust, but they have little to lose with a failed second round pick; and other times their second round picks including DeJuan Blair, Goran Dragic, Luis Scola, and Manu Ginobili greatly outperformed expectations, and several of them contributed to the team's strong success.

However, the draft strategies to achieve the "optimal lineup" differ between [snake](#sec-draftStrategySnake) versus [auction](#sec-draftStrategyAuction) drafts.

### Snake Draft {#sec-draftStrategySnake}

In general, your goal is to draft the team whose weekly starting lineup has the greatest [VORP](#sec-fantasyValueVORP).
Consequently, you are often looking to pick the player with the highest [VORP](#sec-fantasyValueVORP) at a given selection, while keeping in mind (a) the [dropoff](#sec-fantasyValueDropoff) of players at other positions and (b) which players may be available at subsequent picks so that you do not sacrifice too much later value with a given selection.
For instance, if a particular Quarterback has a slightly higher [VORP](#sec-fantasyValueVORP) than a particular Running Back, but the Quarterback is likely to be available at the manager's next pick but the Running Back is likely to be unavailable at their next pick, it might make more sense to draft the Running Back.

### Auction Draft {#sec-draftStrategyAuction}

According to [an analysis](https://harvardsportsanalysis.wordpress.com/wp-content/uploads/2012/04/fantasyfootballdraftanalysis1.pdf) by the Harvard Sports Analysis Collective (archived at <https://perma.cc/P7RX-92UU>), the majority of the manager's salary cap should be spent on the starting lineup, and you should spend less on bench players.
This is known as the "stars and scrubs" draft strategy.
Based on the analysis, the author recommended applying a 10% premium to the top players and a 10% discount to the lower-tiered players.
The idea behind the approach is that a player on your bench does not contribute to the team's points and, thus, most players drafted to your bench do not contribute much to the team's points throughout the season.
That said, bench players can be important in the case of a starter's injury or under-performance.
So, it is recommended to draft starters with lower [uncertainty](#sec-fantasyValueUncertainty) who are safer.
In contrast to your starting lineup, you may look to draft players on your bench who have greater [uncertainty](#sec-fantasyValueUncertainty) for their high reward potential in a low-risk selection given the lower price.
