# Intro to Football and Fantasy {#sec-introFantasy}

This chapter provides a brief primer on football and fantasy football.
If you are already familiar with fantasy football, feel free to skip this chapter.

## Football {#sec-football}

## Fantasy Football {#sec-fantasyFootball}

As noted in the [Introduction](intro.qmd), fantasy football is an online game where participants assemble (i.e., "draft") imaginary teams composed of real-life National Football League (NFL) players.
The participants are in charge of managing and making strategic decisions for their imaginary team to have the best possible team that will score the most points.
Thus, the participants are called "managers".
Managers make decisions such as selecting which players to draft, selecting which players to play (i.e., "start") on a weekly basis, identifying players to pick up from the remaining pool of available players (i.e., waiver wire), and making trades with other teams.

A fantasy football "league" is composed of various imaginary (i.e., "fantasy") teams—and their associated manager.
In the fantasy league, the managers' fantasy teams play against each other.
A fantasy league is commonly composed of 8 or 10 fantasy teams, but leagues can have more or fewer participants/teams.
In the game of fantasy football, participants accumulate points on a weekly basis based on players' actual statistical performances in NFL games.
A participant's goal is to outscore their opponent each week to win matches and ultimately claim victory in the league.

Fantasy football relies heavily on prediction—trying to predict which players will perform best and selecting them accordingly.
