# Player Evaluation {#sec-playerEvaluation}

Evaluating players for fantasy football could be thought of as similar to the process of evaluating companies when picking stocks to buy.
You want to evaluate and compare various assets so that you get the assets with the best value.

There are various domains of criteria we can consider when evaluating a football player's fantasy prospects.
Potential domains to consider include:

- athletic profile
- historical performance
- health
- age and career stage
- situational factors
- matchups
- cognitive and motivational factors

The discussion that follows is based on my and others' *impressions* of which characteristics may be valuable to consider when evaluating players.
However, the extent to which any factor is actually relevant for predicting future performance is an empirical question and should be evaluated empirically.

# Athletic Profile {sec-evalAthleticProfile}

Factors related to a player's athletic profile include factors such as:

- body shape
    - height
    - weight
    - hand size
- body function
    - agility
    - strength
    - speed
    - acceleration/explosiveness
    - jumping ability

In terms of body shape, we might consider a player's height, weight, and hand size.
Height allows players to see over opponents and to reach balls higher in the air.
Thus, greater height is particularly valuable for Quarterbacks and Wide Receivers.
Heavier players are tougher to budge and to tackle.
Greater weight is particularly valuable for Linemen, Fullbacks, and Tight Ends, but it can also be valuable—to a deree—for Quarterbacks, Running Backs, and Wide Receivers.
Hand size is particularly valuable for people catching the ball; thus, a larger hand size is particularly valuable for Wide Receivers and Tight Ends.

In terms of body function, we can consider a player's agility, strength, speed, acceleration/explosiveness, and jumping ability.
For Wide Receivers, speed, explosiveness, and jumping ability are particularly valuable.
For Running Backs, agility, strength, speed, and explosiveness are particularly valuable.

Many aspects of a player's athletic profile are available from the National Football League (NFL) Combine, which is especially relevant for evaluating rookies.
We demonstrate how to import data from the NFL Combine in Section @sec-combine.

# Historical Performance {sec-evalHistoricalPerformance}

> "The best predictor of future behavior is past behavior." – Unknown

> "Past performance does not guarantee future results." – A common disclaimer about investments.

Factors relating to historical performance to consider could include:

- performance in college
    - draft position
- performance in the NFL
- efficiency
- consistency

It is important to consider a player's past performance.
However, the extent to which historical performance may predict future performance may depend on many factors such as (a) the similarity of the prior situation to the current situation, (b) how long ago the prior situation was, and (c) the extent to which the player (or situation) has changed in the interim.
For rookies, the player does not have prior seasons of performance in the NFL to draw upon.
Thus, when evaluating rookies, it can be helpful to consider their performance in college or in their prior leagues.
However, there are large differences between the situation in college and the situation in the NFL, so prior success in college may not portend future success in the NFL.
An indicator that intends to be prognostic of future performance, and that accounts for past performance, is a player's draft position—that is, how early (or late) was a player selected in the NFL Draft.
The earlier a player was selected in the NFL Draft, the greater likelihood that the player will perform well.

For players who have played in the NFL, past performance becomes more relevant because, presumably, the prior situation is more similar (than was their situation in college) to their current situation.
Nevertheless, lots of things change from game to game and season to season: injuries, coaches, coaching strategies, teammates, etc.
So just because a player performed well or poorly in a given game or season does not necessarily mean that they will perform similarly in subsequent games/seasons.
Nevertheless, historical performance is one of the best indicators we have.

We demonstrate how to import historical player statistics in Section @sec-downloadActualStats.
We demonstrate how to calculate historical player statistics in Section @sec-calculateActualStats.
We demonstrate how to calculate historical fantasy points in Section @sec-calculateActualPoints.

In addition to how many fantasy points a player scores in terms of historical performance, we also care about efficiency.
How efficient were they given the number of opportunities they had?
If they were relatively more efficient, they will likely score more points than many of their peers when given more opportunities.
If they were relativelly inefficient, their capacity to score fantasy points may be more dependent on touches/opportunities.
Efficiency might be operationalized by indicators such as yards per passing attempt, yards per rushing attempt, yards per target, yards per reception, etc.

# Health {sec-evalHealth}

Health-related factors to consider include:

- current injury status
- injury history

It is also important to consider a player's past and current health status.
In terms of a player's current health status, it is important to consider whether they are injured or are playing at less than 100% of their typical health.
In terms of a player's prior health status, one can consider their injury history, including the frequency and severity of injuries and their prognosis.

We demonstrate how to import injury reports in Section @sec-injuries.

# Age and Career Stage {sec-evalAgeCareerStage}

Age and career stage-related factors include:

- age
- experience
- touches

A player's age is relevant because of important age-related changes in a player's speed, ability to recover from injury, etc.
A player's experience is relevant because players develop knowledge and skills with greater experience.
A player's prior touches/usage is also relevant, because it speaks to how many hits a player may have taken.
For players who take more hits, it may be more likely that their bodies "break down" sooner.

# Situational Factors {sec-evalSituation}

Situational factors one could consider include:

- team quality
- role on team
- teammates
- opportunity and usage
    - snap count
    - touches/targets
    - red zone usage

Football is a team sport.
A player is embedded within a broader team context; it is important to consider the strength of their team context insofar as it may support— or detract from—a player's performance.
For instance, for a Quarterback, it is important to consider how strong the pass blocking is from the Offensive Line.
Will they have enough time to throw the ball, or will they be constantly under pressure to be sacked?
It is also important to consider the strength of the pass catchers—the Wide Receivers and Tight Ends.
For a Running Back, it is important to consider how strong the run blocking is from the Offensive Line.
For a Wide Receiver, it is important to consider how strong the pass blocking is, and how strong the Quarterback is.

It is also important to consider a player's role on the team.
Is the player a starter or a backup?
Related to this, it is important to consider the strength of one's teammates.
For a given Running Back, if a teammate is better at running the ball, this may take away from how much the player sees the field.
For a given Wide Receiver, if a teammate is better at catching the ball, this may take some targets away from the player.
However, the team's top defensive back is often matched up against the team's top Wide Receiver.
So, if the team's top Wide Receiver is matched up against a particularly strong Defensive Back, the second- and third-best Wide Receivers may more targets than usual.

It is also important to consider a player's opportunity and usage, which are influenced by many factors, including the skill of the player, the skill of their teammates, the role of the player on the team, the coaching style, the strategy of the opposing team, game scripts, etc.
In terms of the player's opportunity and usage, how many snaps do they get?
How many touches and/or targets do they receive?
Being on the field for more snaps and receiving more touches and/or targets means that the player has more opportunities to score fantasy points.
Are they targeted in the red zone?
Red zone targets are more likely to lead to touchdown scoring opportunities, which are particularly valuable in fantasy football.

# Matchups {sec-evalMatchups}

Matchup-related factors to consider include:

- strength of schedule
- weekly matchup

Another aspect to consider is how challenging their matchup(s) and strength of schedule is.
For a Quarterback, it is valuable to consider how strong the oppenent's passing defense is.
For a Running Back, how strong is the running defense?
For a Wide Receiver, how strong is the passing defense and the Defensive Back that is likely to be assigned to guard them?

# Cognitive and Motivational Factors {sec-evalCogMotivational}

Other factors to consider include cognitive and motivational factors
Cognitive and motivational factors one could consider include:

- reaction time
- knowledge and intelligence
- work ethic and mental toughness
- incentives
    - contract performance incentives
    - whether they are in a contract year

A player's knowledge, intelligence, and reaction time can help them gain an upper-hand even when they may not be the fastest or strongest.
A player's work ethic and mental toughness may help them be resilient and persevere in the face of challenges.
Contact-related incentives may lead a player to put forth greater effort.
For instance, a contract may have a performance incentive that provides a player greater compensation if they achieve a particular performance milestone (e.g., receiving yards).
Another potential incentive is if a player is in what is called their "contract year" (i.e., the last year of their current contract).
If a player is in the last year of their current contract, they have an incentive to perform well so they can get re-signed to a new contract.
