# Research Methods {#sec-researchMethods}

## Getting Started {#sec-researchMethodsGettingStarted}

### Load Packages {#sec-researchMethodsLoadPackages}

```{r}

```

## Sample vs Population {#sec-sampleVsPopulation}

In research, it is important to distinguish between the sample and the target population.
The target *population* is who you want your study's findings to generalize to.
For instance, if we want our findings to lead to inferences we can draw regarding all current NFL players, then NFL players are our target population.
However, despite our best efforts to recruit all NFL players into our study, we may not succeed in doing that.
The participants (i.e., people or players) who we successfully recruit to be in our study represent our *sample*.

It is rare for the sample to include all people who are in the target population.
It can be costly to recruit large samples, and many potential participants may decline to participate for a variety of reasons (insufficient time, lack of interest in the study, distrust of scientists, etc.).
Thus, our goals are (a) to recruit as many people from the population as possible and (b) for the sample to be as *representative* of the population as possible.

For increasing the representativeness of the sample (with respect to the population), we might conduct a *random sample*, in which each person in the population (i.e., each NFL player) has equal likelihood of being selected.
For instance, we might randomly select 250 players to recruit to the study.
True random samples, though strong in aspiration, are difficult and costly to achieve.
In reality, many researchers conduct convenience sampling.
A convenience sample is recruited because it is convenient (i.e., less costly and time-consuming).

For instance, many studies examine college students—in part, because they are easy to recruit.
If our target population is NFL players but we are unable to recruit NFL players into our study, we could easily recruit a large sample of college students.
Although the convenience sample may afford a very large sample, the college student sample may not be representative of the target population (NFL players).
Thus, the findings in our study may not *generalize* to NFL players—that is, what we learn in college students may not apply in the same way among NFL players.
For instance, if we learn that consumption of sports drinks (compared to drinking only water) improves running speed among college students, that may not be the case among NFL players.

## Research Designs {#sec-researchDesigns}

There are three broad types of research designs:

- experiment
- correlational/observational study
- case study

### Experiment {#sec-experiment}

In an *experiment*, there are one or more things that we manipulate to see how the manipulation influences the process of interest.
The variable that we manipulate is the *independent variable*.
By contast, the *dependent variable* is the variable that we evaluate to determine whether it was influenced by the manipulation (i.e., by the independent variable).

For instance, we may be interested to evaluate whether players perform better (e.g., run faster) if they drink a sports drink compared when they drink only water.
Our hypothesis might be that players will be expected to perform better when they drink a sports drink (compared to when they drink only water).
To this this research question and hypothesis, we might conduct an experiment by randomly assigning some players during practice to receive a sports drink and some players to receive only water.
In this case, our independent variable is whether the player receives a sports drink.
Our dependent variable might be their 40-yard dash time during practice.

### Correlational/Observational Study {#sec-correlationalStudy}

In a correlational (aka observational) study, we do not manipulate a variable to see how the manipulation influences another variable.
Instead, we examine how two variables, a predictor and an outcome variable, are associated.
The hypothesized cause is called the predictor variable.
The hypothesized effect is called the outcome variable.
In this way, the predictor variable is similar to the independent variable, and the outcome variable is similar to the dependent variable.
However, unlike the independent and dependent variables in an experiment, the predictor and outcome variables in a correlational study are not manipulated.

For instance, to use a correlational study to test the possibility that players who drink sports drinks perform better than players who drink only water, we could examine whether the players who drink sports drinks during a game score more fantasy points than players who drink only water during the game.
In this case, our predictor variable is whether the players drinks sports drinks during a game.
Our outcome variable is the number of fantasy points the player scored.

### Case Study {#sec-caseStudy}

In a case study, we assess a small sample of individuals (commonly only one person or a few people), often with rich qualitative information.
Themes may be coded from the qualitative information, which may help inform inferences about whether some process may have played a role in influencing the outcome of interest.

For instance, to use a case study to evalute the possibilty that players who drink sports drinks perform better than players who drink only water, we could conduct an in-depth interview with a player.
In the interview, we might ask the player how they performed in games with versus without a sports drink and have them discuss whether they believe the sports drink improved their performance (and if so, how).
Then, based on the player's responses, we might code the responses to extract themes and to make a qualitative judgement of whether or not the player likely performed better during games in which they had a sports drinl

### Other Features of the Research Design {#sec-researchDesignOtherFeatures}

#### Number of Timepoints {#sec-researchDesignTimepoints}

In addition to whether the research design is an [experiment](#sec-experiment), [correlational/observational study](#sec-correlationalStudy), or a [case study](#sec-caseStudy), a research design can also have one or multiple timepoints.
The differing number of timepoints allow studies to be characterized as one of the following:

- cross-sectional
- longitudinal

##### Cross-Sectional {#sec-crossSectional}

A *cross-sectional study* is a study with one timepoint.

For instance, in a cross-sectional study evaluating whether having a sports drink improves player performance, we might assess players' drinking behavior and performance during only game 1.

##### Longitudinal Design {#sec-longitudinal}

A *longitudinal study* is a study with more than one timepoint.
When the <u>same measures<u> are assessed at each of multiple timepoints, we refer to this as a "repeated measures" design.

In a longitudinal study evaluating whether having a sports drink improves player performance, we might assess players' drinking behavior and performance during each game of the season, and possibly across multiple seasons.

#### Within- or Between-Subject {#sec-withinBetweenSubject}

A research design can also be within-subject, between-subject, or both.

##### Within-Subject Design {#sec-withinSubject}

A *within-subject design* is one in which each participant (i.e., person or player) receives multiple levels of the independent variable (or predictor).

For instance, in an experiment evaluating whether having a sports drink improves player performance, we might assign players to drink the sports drink in the first half of the game and to drink only water in the second half of the game.
Or we could assign some of the players to drink sports drink in the first half and water in the second half, and assign the other players to drink water in the first half and sports drink in the second half.

In a correlational study evaluating whether having a sports drink improves player performance, we might evaluate how within-person changes in sports drink consumption are associated with within-person changes in performance.
That is, we could evaluate, when a given player has a sports drink (or more sports drinks), do they perform better than <u>when the same individual</u> has only water (or fewer sports drinks)?

##### Between-Subject Design {#sec-betweenSubject}

A *between-subject design* is one in which each participant (i.e., person or player) receives only one level of the independent variable.

For instance, in an experiment evaluating whether having a sports drink improves player performance, we might assign some players to drink the sports drink but the other players to drink only water.

In a correlational study evaluating whether having a sports drink improves player performance, we might evaluate whether people who drink sports drinks tend to perform better than players who drink only water.
Or, we could evaluate whether players who drink more sports drinks perform better than players who drink fewer sports drinks (i.e., whether the number of sports drinks consumed during a game is correlated with player performance).

## Research Design Validity {#sec-researchDesignValidity}

Research design validity involves the accuracy of inferences from a study.
There are three types of research design validity:

- internal validity
- external validity
- conclusion validity

### Internal Validity {#sec-internalValidity}

Internal validity is the extent to which we can be confident that the associations identified in the study are causal.

### External Validity {#sec-externalValidity}

External validity is the extent to which we can be confident that findings from the study play out similarly in the real world—that is, the findings generalize to the target population.

### Conclusion Validity {#sec-externalValidity}

Conclusion validity is the extent to which a study's conclusions are reasonable about the association among variables based on the data.
That is, were the correct statistical analyses performed, and are the interpretations of the findings from those analyses correct?

## Levels of Measurement {#sec-levelsOfMeasurement}

It is important to know the levels of measurement of your data, because the level(s) of measurement of your data constrain the types of comparisons and analyses that you can meaningfully perform.
There are four levels of measurement that any variable can have:

- nominal
- ordinal
- interval
- ratio

Each is described below:

### Nominal {#sec-nominal}

A variable is considered nominal if it is composed of qualitative classifications.
You cannot meaningfully evaluate whether one number in the variable is larger than another number in the variable because higher numbers do not reflect higher levels of the concept.
Examples of nominal variables include:

- sex (e.g., 1 = male; 2 = female)
- race (e.g., 1 = American Indian; 2 = Asian; 3 = Black; 4 = Pacific Islander; 5 = White)
- ethnicity (e.g., 0 = Non-Hispanic/Latino; 1 = Hispanic/Latino)
- zip code
- jersey number

A football player's jersey number is an example of a nominal variable.
A jersey number of 7 is not higher on whatever concept of interest compared to a jersey number of 6.

To examine the central tendency of a nominal variable, you can determine the mode, but you cannot calculate a mean or median.

### Ordinal {#sec-ordinal}

A variable is considered ordinal if the classifications are ordered.
However, ordinal variables do not have equally spaced intervals.
Examples of ordinal intervals include:

- likert response scales (e.g., 1 = strongly disagree; 2 = disagree; 3 = neutral; 4 = agree; 5 = strongly agree)
- educational attainment (e.g., 1 = no formal education; 2 = elementary school; 3 = middle school; 4 = high school; 5 = college; 6 = graduate degree)
- academic grades on A–F scale (e.g., 1 = A; 2 = B; 3 = C; 4 = D; 5 = F)
- player rank (1 = 1st; 2 = 2nd; 3 = 3rd, etc.)

A football player's fantasy rank is an example of an ordinal variable.
A player with a fantasy rank of 1 has a higher rank than a player with a rank of 2, but it is not known how far apart each player is—i.e., the intervals do not all reflect the same distance.
For instance, the distance between the top-ranked player and the 2nd-best player might be 30 points, whereas the distance between the 2nd-best player and the 3rd-best player might be 2 points.

To examine the central tendency of ordinal data, the median and mode are most appropriate; however, the mean may be used (unlike for nominal data).

### Interval {#sec-interval}

A variable is considered interval if the classifications are ordered (similar to ordinal data) and have equally spaced intervals (unlike ordinal data).
However, interval variables do not have a meaningful zero that reflects absence.
Examples of interval data include:

- temperature on the Fahrenheit or Celsius scale
- time of day

For instance, the temperature difference between 80 and 90 degrees Fahrenheit is the same as the temperature difference between 90 and 100 degrees Fahrenheit.
However, 0 degrees Fahrenheit does not reflect absence of temperature/heat.

Interval data can be meaningfully added or subtracted.
For instance, if a game starts at 4 pm and ends at 7 pm, you know the game lasted 3 hours ($7 - 4 = 3$).
However, interval data cannot be meaningfully multiplied or divided.
For instance, 100 degrees Fahrenheit is not twice as hot as 50 degrees Fahrenheit.

To examine the central tendency of interval data, you can compute the mean, median, or mode.

### Ratio {#sec-ratio}

A variable is considered ratio if the classifications are ordered (similar to ordinal data), have equally spaced intervals (like interval data), and have an absolute zero point that reflects absence of the concept.
Examples of ratio data include:

- height
- weight
- age
- distance
- speed
- volume
- time elapsed
- income
- years of formal education
- points in football

For instance, points in football has order, equally spaced intervals, and an absolute zero—a team cannot score less than zero points, and zero points reflects absence of points (though it could be argued to be interval data because zero points does not reflect absence of skill.)

Ratio data can be meaningfully added, subtracted, multiplied, or divided.
A player who weighs 350 pounds weighs twice as much as someone who weighs 175 pounds.

To examine the central tendency of ratio data, you can compute the mean, median, or mode.

## Measurement Validity {#sec-measurementValidity}

### Reliability {#sec-reliability}

### Validity {#sec-validity}

